### ISSUE TITLE
compute() does not break table lineage for Sparklyr 0.7.0.9031

### ISSUE THREAD

**Issue by MZLABS** [sparklyr/sparklyr#1026]
Callling `compute()` does not appear to break table lineage for `sparklyr` 0.7.0.9031.  The symptom is computation gets slower and slower as more and more iterated or nested calculation is performed.  Eventually the cluster throws a "Java out of memory" exception.  

I would be happy to use `sdf_checkpoint()` for this, but that doesn't currently have enough documentation for me to figure what it does and how to use it. In particular can you control the name and temporary or non-temporary nature of such tables  (not trying to persist them or do anything odd, just want to know if they leak and how to delete them when I am done with them).

Attached is the ".Rmd" source and ".html" rendering of the effect.  

This is something I ran into at an `RStudio Server Pro` client in a longish real-world situation.  The behavior and error message were similar to what I see here.  I saw similar behavior with `sparklyr` version 0.6.3.  This issue may be related to [`sparklyr` issue 783](https://github.com/rstudio/sparklyr/issues/783).

[ComputeIssue.txt](https://github.com/rstudio/sparklyr/files/1318857/ComputeIssue.txt)
[ComputeIssue.pdf](https://github.com/rstudio/sparklyr/files/1318858/ComputeIssue.pdf)

**Comment by kevinykuo** [comment]
`compute()` isn't supposed to break lineage; it just calls `tbl_cache()`. Do we have documentation that implies otherwise?

Could you give this a shot: replace `compute()` with `sdf_checkpoint() %>% compute()` – this will truncate lineage *and* cache – then see if it produces a better looking chart?

**Comment by kevinykuo** [comment]
Looking at the stack trace, this could also be due to GC grinding to a halt because of churn (adding/deleting stuff from JVM). If the above comment doesn't help, I'd try `sdf_persist()` (which defaults to storage level `MEMORY_AND_DISK` instead of `compute()`.

I wonder if we should add a `storage_level` argument to `compute()`...

**Comment by MZLABS** [comment]
From `help(compute)`:

> compute() stores results in a remote temporary table

To my mind (and maybe I should not have used the term lineage).  That would (in database terms) materialize a view.  I.e.: make a table that is independent of all the steps prior (even letting us delete prior stuff).

Again what is the lifespan of `sdf_checkpoint()`.  Unlike `compute()` it doesn't seem to take a name (so I don't know what to delete later when I am done).

**Comment by kevinykuo** [comment]
The contents of the checkpointing directory is persistent, i.e. they'll be around after your close the session and you'd have to clean it up manually AFAIK.

BTW I got the operations backwards, you'd likely want to do `compute() %>% sdf_checkpoint()` or `sdf_persist() %>% sdf_checkpoint()`.

Here's some detailed info if you want to read more about checkpointing: https://github.com/JerryLead/SparkInternals/blob/master/markdown/english/6-CacheAndCheckpoint.md

**Comment by JohnMount** [comment]
I've [knitted an example](https://github.com/WinVector/BigDataRStrata2017/blob/master/extras/ComputeIssue/ComputeIssue.md).  I still think `compute()` breaks `dplyr` expectations by failing on long calculations that have trivial data.

**Comment by javierluraschi** [comment]
@MZLABS Could you explain why we need to execute `compute()` over a loop? My guess is that there might be a better approach here since this is a pattern I don't see used in Spark, it would be equivalent to running something in Scala like:

```scala
var rdd = sc.parallelize(List.range(0, 10))
for( a <- 1 until 10) {
  rdd = rdd.map(x => x + 1)
}
rdd.collect()
```

While possible, for large values, this would not be an approach I would recommend in Spark since the loop will cause the lineage of the final rdd to have as many steps as iterations in the loop and Spark is not optimized for this. The example above with n=10 would create the following graph which even for small iterations already shows some of the challenges of this approach:

<img width="1439" alt="screen shot 2017-10-16 at 1 46 53 pm" src="https://user-images.githubusercontent.com/3478847/31634509-b0e0535c-b278-11e7-8948-b86e108efee2.png">

Also, I think we need more evidence that lineage is the cause of the slowdown. Since `compute()` stores results in-memory and is being called over-and-over, it is possible that this is causing the cluster to be under pressure and slowdown because of memory pressure and not from past lineage.

Overall, my guess is that `compute()` is not needed here at all but rather something like `sdf_checkpoint()`; however, hard to provide a recommendation without understanding what you are trying to accomplish.

**Comment by javierluraschi** [comment]
@JohnMount Regarding the attached markdown reference, I don't believe knitting this is trivial in Spark since we have this loop:

```
for(nsteps in c(1, 5, 10, 20, 50, 75, 100)) {
  for(rep in seq_len(3)) {
    for(fname in names(fnMap))
```

For `100`, Spark will create a graph of at-least 100 nodes (probably much bigger than that since this would be a best-case scenario), which is not a trivial cluster execution task even if the data is trivial.

It was not until Spark 2.0 that I start seeing fixes being pushed to optimize large graphs, but my guess, is that this is still an area of active development in Spark.

That said, I'm almost sure we can find a way to avoid creating large execution grpahs if you provide us with more information with the task at hand.

**Comment by MZLABS** [comment]
@JohnMount / @MZLABS here.  The `compute()` was an attempt to try to prevent failure on the very many `mutates()`.  The loop is just modeling I have a client code sequence that is a huge number of mutates and this dies.  I assumed it would die without the `compute()` (that the `compute()` isn't causing the problem, just failing to fix it).  The issue is "large graphs" is indeed a silly thing for a view based data system (such as `Spark`) but it is easy for a standard valued based system (which is where code being ported is coming from).

**Comment by javierluraschi** [comment]
@MZLABS @JohnMount thanks, this gives us better understanding but I still have some questions: Are the 90+ select calculations independent of each other? If they are, we should be able to talk about one issue at the time to troubleshoot why they fail on Spark. If there are dependencies, how are they depending between them?  Is it that some select statements in the DB  system use views? Do you know if those views are materialized?

If I assume that the views are indeed materialized, then I think using `compute()` or `sdf_persist()` makes sense. The next step would be to understand why the queries are not fitting into memory or disk for `sdf_persist()`.

**Comment by JohnMount** [comment]
In one instance the calculations are as follows: an R function that performs a number of mutates (20, 7, or 2 depending on how much we polish the code) is called.     This function takes in about 6 columns and adds 3 columns to the data.  The data we are working with is 600 columns by 16 million rows on Spark (Hive back-end).  What kills us is applying this function 30 times (so appending 90 more columns) blows up.  The stacked views get way too long.

We are not explicitly using views or a lot of direct SparkSQL- all steps are through dplyr/Sparklyr. So when I say "view" or "view stacking" I was imprecise: I mean the sort of nested queries Sparklyr builds.  So sorry about brining in view/materialized terminology.

From experience (confirmed in the example in this issue) we have found `compute()` does not fix the blow-up.  `sdf_persist()` also did not work (though perhaps because I was trying it conjunction with a `compute()`.  I think `sdf_checkpoint()` could help, but with the wide data that is prohibitively expensive.  We are researching other work-arounds and will take a look at the `sdf_checkpoint()`.
