### ISSUE TITLE
spark_apply not working 

### ISSUE THREAD

**Issue by northeastloon** [sparklyr/sparklyr#1432]
I have the following spark DataFrame cached in memory (with local mode):
```r
Observations: ??
Variables: 12
$ COUNTRY     <int> 218, 218, 218, 218, 218...
$ illit       <dbl> 0, 0, 0, 0, 0...
$ isol_illit  <dbl> 0, 0, 0, 0, 0...
$ AGE         <int> 29, 25, 47, 39, 18...
$ age_cat     <chr> "25-35", "25-35", "45-54", "35-44", "15-24", ...
$ SEX         <dbl> 0, 1, 0, 1, 1...
$ hh_size     <dbl> 4, 4, 6, 6, 6, ...
$ perwt_std   <dbl> 1.340802e-06, 1.340802e-06, 1.340802e-06, 1.340802e-06, 1.340802e-06...
$ rural       <dbl> 0, 0, 0, 0, 0, ...
$ marst_rec   <int> 2, 2, 2, 2, 1...
$ prop_unrel  <dbl> 0, 0, 0, 0, 0...
$ nchild10_14 <dbl> 0, 0, 1, 1, 1...
```
I can run the following ml function fine
```r
model_pooled1 <- model_data %>%
  ml_logistic_regression(formula = isol_illit ~ rural + AGE + SEX + hh_size + marst_rec + prop_unrel + nchild10_14,  weight_col = "perwt_std",    max_iter  = 25L)
```
However if I try do use glm through spark_apply...
```r
model_country1 <- model_data %>%
  spark_apply(
    function(e) broom::tidy(glm(formula = isol_illit ~ rural + AGE + SEX + hh_size + marst_rec + prop_unrel + nchild10_14, weights = perwt_std, family = "binomial", data = e)),
    names = c("term", "estimate", "std.error", "statistic", "p.value"),
    group_by = "COUNTRY") 
```
...I get the following error: 
```r
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\~\AppData\Local\Temp\RtmpUBKRZu\file1fe07d436c2_spark.log': Permission denied
```
I get the same error removing the group_by command. It is also replicated on a windows 10 machine running r version 3.4.4.
```r
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2      viridis_0.5.1       viridisLite_0.3.0   tmap_1.11-2         rgdal_1.2-18        sp_1.2-7           
 [7] stringr_1.3.0       tidyr_0.8.0         broom_0.4.4         countrycode_1.00.0  ggplot2_2.2.1       ipumsr_0.1.1       
[13] dplyr_0.7.4         sparklyr_0.7.0-9026

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2   deldir_0.1-15      class_7.3-14       gdalUtils_2.0.1.7  leaflet_1.1.0      rprojroot_1.3-2   
  [7] satellite_1.0.1    base64enc_0.1-3    dichromat_2.0-0    rstudioapi_0.7     xml2_1.2.0         codetools_0.2-15  
 [13] splines_3.4.3      R.methodsS3_1.7.1  mnormt_1.5-5       knitr_1.20         config_0.3         geojsonlint_0.2.0 
 [19] jsonlite_1.5       tmaptools_1.2-4    dbplyr_1.2.1       png_0.1-7          R.oo_1.21.0        rgeos_0.3-26      
 [25] shiny_1.0.5        compiler_3.4.3     httr_1.3.1         backports_1.1.2    mapview_2.3.0      assertthat_0.2.0  
 [31] Matrix_1.2-12      lazyeval_0.2.1     cli_1.0.0          htmltools_0.3.6    tools_3.4.3        coda_0.19-1       
 [37] gtable_0.2.0       glue_1.2.0         reshape2_1.4.3     rappdirs_0.3.1     gmodels_2.16.2     V8_1.5            
 [43] Rcpp_0.12.16       raster_2.6-7       spdep_0.7-7        gdata_2.18.0       nlme_3.1-131       udunits2_0.13     
 [49] iterators_1.0.9    crosstalk_1.0.0    psych_1.8.3.3      mime_0.5           devtools_1.13.5    gtools_3.5.0      
 [55] XML_3.98-1.10      LearnBayes_2.15.1  MASS_7.3-48        scales_0.5.0       parallel_3.4.3     expm_0.999-2      
 [61] RColorBrewer_1.1-2 yaml_2.1.18        curl_3.2           memoise_1.1.0      geosphere_1.5-7    gridExtra_2.3     
 [67] stringi_1.1.7      jsonvalidate_1.0.0 foreach_1.4.4      e1071_1.6-8        boot_1.3-20        spData_0.2.8.3    
 [73] rlang_0.2.0        pkgconfig_2.0.1    bitops_1.0-6       lattice_0.20-35    purrr_0.2.4        bindr_0.1.1       
 [79] sf_0.6-1           htmlwidgets_1.0    tidyselect_0.2.4   osmar_1.1-7        plyr_1.8.4         magrittr_1.5      
 [85] R6_2.2.2           DBI_0.8            pillar_1.2.1       haven_1.1.1        foreign_0.8-69     withr_2.1.2       
 [91] units_0.5-1        RCurl_1.95-4.10    tibble_1.4.2       crayon_1.3.4       rmapshaper_0.4.0   utf8_1.1.3        
 [97] KernSmooth_2.23-15 grid_3.4.3         forcats_0.3.0      digest_0.6.15      classInt_0.1-24    webshot_0.5.0     
[103] xtable_1.8-2       httpuv_1.3.6.2     R.utils_2.6.0      openssl_1.0.1      stats4_3.4.3       munsell_0.4.3  
```

**Comment by javierluraschi** [comment]
Need to check the worker logs and find entries containing `INFO sparklyr: RScriptt` or `ERROR sparklyr: RScript` to diagnose problems in `spark_apply()`.

**Comment by marcoscattolin** [comment]
I ran into this as well. Looks like it's related to the fact that dataframe includes a column of type org.apache.spark.ml.linalg.VectorUDT

Check following code:

# Load packages
library(sparklyr)
library(dplyr)


# set spark context
sc <- spark_connect(master = "local", version = "2.2.0")


# simple data frame -- works fine
iris_tbl <- copy_to(sc, iris, "iris", overwrite = T) %>%
        sdf_repartition(partitions = 3, partition_by = "Species") %>%
        sdf_register("iris")				

iris_tbl %>%
        spark_apply(function(x) head(x,1))

# data frame with linalg -- gives "Error in file(con, "r") : cannot open the connection ..."
iris_vect_tbl <- iris_tbl %>%
        sdf_repartition(partitions = 3, partition_by = "Species") %>%
        ft_vector_assembler(input_cols = c("Sepal_Length","Sepal_Width","Petal_Length","Petal_Width"), "vec") %>%
        sdf_register("iris_vec")

iris_vect_tbl %>%
        spark_apply(function(x) head(x,1))

Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  Italian_Italy.1252          
 tz       Europe/Berlin               
 date     2018-05-11                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.2.0   2017-04-11 CRAN (R 3.4.0)
 backports    1.1.1   2017-09-25 CRAN (R 3.4.1)
 base       * 3.4.1   2017-06-30 local         
 base64enc    0.1-3   2015-07-28 CRAN (R 3.4.1)
 bindr        0.1     2016-11-13 CRAN (R 3.4.0)
 bindrcpp   * 0.2     2017-06-17 CRAN (R 3.4.1)
 broom        0.4.2   2017-02-13 CRAN (R 3.4.0)
 cli          1.0.0   2017-11-05 CRAN (R 3.4.4)
 compiler     3.4.1   2017-06-30 local         
 config       0.2     2016-08-02 CRAN (R 3.4.2)
 crayon       1.3.4   2017-09-16 CRAN (R 3.4.2)
 datasets   * 3.4.1   2017-06-30 local         
 DBI        * 0.7     2017-06-18 CRAN (R 3.4.2)
 dbplyr       1.1.0   2017-06-27 CRAN (R 3.4.2)
 devtools     1.13.3  2017-08-02 CRAN (R 3.4.2)
 digest       0.6.15  2018-01-28 CRAN (R 3.4.3)
 dplyr      * 0.7.4   2017-09-28 CRAN (R 3.4.2)
 foreign      0.8-69  2017-06-22 CRAN (R 3.4.1)
 glue         1.1.1   2017-06-21 CRAN (R 3.4.1)
 graphics   * 3.4.1   2017-06-30 local         
 grDevices  * 3.4.1   2017-06-30 local         
 grid         3.4.1   2017-06-30 local         
 htmltools    0.3.6   2017-04-28 CRAN (R 3.4.0)
 httpuv       1.3.5   2017-07-04 CRAN (R 3.4.2)
 httr         1.3.1   2017-08-20 CRAN (R 3.4.2)
 jsonlite     1.5     2017-06-01 CRAN (R 3.4.0)
 lattice      0.20-35 2017-03-25 CRAN (R 3.4.1)
 lazyeval     0.2.1   2017-10-29 CRAN (R 3.4.4)
 magrittr     1.5     2014-11-22 CRAN (R 3.4.0)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.2)
 methods    * 3.4.1   2017-06-30 local         
 mime         0.5     2016-07-07 CRAN (R 3.4.0)
 mnormt       1.5-5   2016-10-15 CRAN (R 3.4.0)
 nlme         3.1-131 2017-02-06 CRAN (R 3.4.1)
 openssl      0.9.7   2017-09-06 CRAN (R 3.4.2)
 parallel     3.4.1   2017-06-30 local         
 pillar       1.2.1   2018-02-27 CRAN (R 3.4.4)
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.4.0)
 plyr         1.8.4   2016-06-08 CRAN (R 3.4.0)
 psych        1.7.8   2017-09-09 CRAN (R 3.4.2)
 purrr        0.2.4   2017-10-18 CRAN (R 3.4.2)
 R6           2.2.2   2017-06-17 CRAN (R 3.4.2)
 rappdirs     0.3.1   2016-03-28 CRAN (R 3.4.2)
 Rcpp         0.12.14 2017-11-23 CRAN (R 3.4.3)
 reshape2     1.4.2   2016-10-22 CRAN (R 3.4.0)
 rlang        0.2.0   2018-02-20 CRAN (R 3.4.4)
 rprojroot    1.2     2017-01-16 CRAN (R 3.4.2)
 rstudioapi   0.7     2017-09-07 CRAN (R 3.4.2)
 shiny        1.0.5   2017-08-23 CRAN (R 3.4.2)
 sparklyr   * 0.8.2   2018-05-06 CRAN (R 3.4.4)
 stats      * 3.4.1   2017-06-30 local         
 stringi      1.1.5   2017-04-07 CRAN (R 3.4.0)
 stringr      1.2.0   2017-02-18 CRAN (R 3.4.0)
 tibble       1.4.2   2018-01-22 CRAN (R 3.4.4)
 tidyr        0.7.2   2017-10-16 CRAN (R 3.4.2)
 tools        3.4.1   2017-06-30 local         
 utf8         1.1.3   2018-01-03 CRAN (R 3.4.4)
 utils      * 3.4.1   2017-06-30 local         
 withr        2.0.0   2017-07-28 CRAN (R 3.4.2)
 xtable       1.8-2   2016-02-05 CRAN (R 3.4.0)
 yaml         2.1.14  2016-11-12 CRAN (R 3.4.0)

**Comment by harryprince** [comment]
I got the same issue.

the name of `p.value` is wrong, you should rename `p.value` as `p_value`.

@northeastloon

**Comment by harryprince** [comment]
@northeastloon you can find your log at Spark UI => Excetuor => worker `stdout` or `stderr`

**Comment by lucavignali** [comment]
I have problem similar to northeastloon. 

Thus I tried the example from here [sparklyr distributed r](https://spark.rstudio.com/guides/distributed-r/). 
That is as follows:

 _trees_tbl %>%
  spark_apply(function(e) __nrow__(e))_
and it WORKED.

However, if I change like this (just change the function that comes from base R anyway):

 _trees_tbl %>%
  spark_apply(function(e) __dim__(e))_
And it is NOT WORKING as I receive similar problem as reported by northeastloon.

**Comment by cc20002002** [comment]
same problem here..

**Comment by JordanCuevas** [comment]
I'm having the same problem one year later. Is there a plan to resolve this?

**Comment by JannicCutura** [comment]
same problem

**Comment by gwd666** [comment]
same problem

**Comment by anvariala** [comment]
Still same problem, 12th April 2020.

Tried all fixes posited online, no dice :(

Very frustrating to hit this wall after coming so far on death-march project... pls halp! :)

**Comment by jfarland** [comment]
I believe I found a solution for this. I started running into this same problem yesterday and couldn't figure it out for the life of me. I believe the issue comes about from using group_by() in a spark_apply() call when the resulting partitions and shuffle doesn't fit into the default heap size in the JVM. For my work, I am using an EC2 instance with a fair amount of memory, so one may want to scale these configs accordingly, but the key is to increase the default java heap memory with the following config: spark.driver.extraJavaOptions` <- 'append "-Xmx8g"'.

Here's my full config for my project. Hopefully this may be helpful to others.

Sys.setenv(SPARK_HOME = '/opt/spark/')
Sys.setenv(SPARK_VERSION = '3.0.0')

# Set memory allocation for whole local Spark instance
Sys.setenv("SPARK_MEM" = "150g")

options(java.parameters = "-Xmx8000m")

# Set driver and executor memory allocations
config <- spark_config()
config$spark.driver.memory <- "30G"
config$spark.executor.memory <- "60G"
config$spark.memory.fraction <- 0.9
config$`sparklyr.shell.driver-memory` <- '30G'
config$`sparklyr.shell.executor-memory` <- '30G'
config$spark.driver.extraJavaOptions <- 'append "-Xmx8g"'

# Connect to Spark instance
sc <- spark_connect(master = "local", config = config)

**Comment by yitao-li** [comment]
I think there are several issues here:

- `spark_apply()` memory footprint -- There are some changes in sparklyr 1.7 that may help (e.g., support for `qs` or custom serialization for `spark_apply()`, using broadcast variables for `spark_apply()` context objects, etc). Those changes reduce the serialized size of Spark tasks generated by `spark_apply()`. They may reduce the memory footprint of `spark_apply()` to some extent.

- `trees_tbl %>% spark_apply(function(e) dim(e))` not working -- Please provide a complete, self-contained repro if you wish this issue to be addressed. I just tried `sdf <- copy_to(sc, tibble::tibble(x = seq(100)), repartition = 5)` followed by `spark_apply(sdf, function(e) dim(e)) %>% print()` and it seems to work fine with sparklyr 1.7. There may be some caveats with `dim()` though (e.g., it will error out when you give it some particular type of input, in which case you would need to look at Spark worker log to find out what input caused your spark_apply() closure to fail). Anyhow, this seems to be some base R issue on your side, rather than a sparklyr issue. If you see anything that suggest otherwise, please let me know.

- Things not working on Windows 10 -- Many other issues mentioned here seem to be Windows-specific, and also some seem to only occur with a particular version of Windows. Unfortunately, at the moment there is simply enough `sparklyr` contributors who also have Windows experise to suggest any workarounds. `spark_apply()` is known to work well on *nix platforms so the presence of random issues on Windows suggests there is something Windows-specific we need to do to workaround such issues. I don't know what those workarounds are (due unfamiliarity with how everything in Windows works), and so far none of the other `sparklyr` contributors have suggested anything along that direction either. Any idea how to make things work better on Windows will be greatly appreciated. All I can think of at the moment is Windows won't allow you to delete a file that is open (unlike *nix) and this seems to break things randomly every once in a while. Sparklyr itself does not make any assumption that is platform-specific but some bits and pieces sparklyr depends on may make those assumptions and then end up not working on Windows every once in a while.
