### ISSUE TITLE
add funciton's documentations 

### ISSUE THREAD

**Issue by patarol** [sparklyr/sparklyr#1672]
I'm new using `sparklyr` but no in `R`.

I'm trying to use [`ft_one_hot_encoder`](http://spark.rstudio.com/reference/ft_one_hot_encoder/) however is somehow difficult to use it since there're no examples in the function's documentation. 

So, I've searched for some example and was no lucky.  So I started to look at the package's documentation and all function I've looked up don't have examples in their documentation. 

When are you planning to add the examples?

Thank you

**Comment by benmwhite** [comment]
The ft_* functions are usually wrappers for Scala/Spark operations. Spark uses vector/list-valued columns pretty often, so that's usually a source of confusion for a lot of users more familiar with Base R or the tidyverse. [Usually the original Scala documentation helps for figuring out things like input and output formats in certain cases.](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.feature.OneHotEncoderEstimator) Those helped me out with some issues I've had before, however I have no idea if that's related to the specific problem you're having since you didn't provide any code examples or error messages in your issue report.

**Comment by patarol** [comment]
Hey @benmwhite thank you for your answer. I was tried to create dummy variables using `ft_one_hot_encoder`. The data is too big to post here and I got a strange error from java... 

I had to create my own fucntion because I was no able to use this function. 

Glad that you guys are working on documentation. This is an amazing work and also an amazing package.

Thank you.

**Comment by benmwhite** [comment]
No problem! I'm not actually a project contributor, I just use sparklyr a lot and follow it here on GitHub. Not sure if you've seen this already but if you have casual questions that might be too short for a standalone StackOverflow post or an official issue report you can also try asking on [the sparklyr gitter chat room](https://gitter.im/rstudio/sparklyr).

**Comment by patarol** [comment]
@benmwhite  Thank you for your time!!
I'll consider this page next time. 
Thank you again!
