### ISSUE TITLE
PIC

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1767]
https://issues.apache.org/jira/browse/SPARK-15784

**Comment by yitao-li** [comment]
NOTE: because PIC (https://spark.apache.org/docs/3.0.0/api/java/org/apache/spark/ml/clustering/PowerIterationClustering.html) is not a `org.apache.spark.ml.PipelineStage`, we do not support ml_pipeline-related interface methods for PIC in sparklyr. The only supported use case is applying `ml_power_iteration()` to a Spark dataframe containing the affinity matrix. The Spark dataframe must have a src column, a dst column, and a weight column as described in the PIC paper, with weight column being non-negative.
