### ISSUE TITLE
Higher order functions

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1773]
https://issues.apache.org/jira/browse/SPARK-23899

**Comment by mattpollock** [comment]
any movement on this issue?

**Comment by kevinykuo** [comment]
Haven't looked into this too much, but is this functionality being handled by the SQL interpreter (which we'd get for free) or is there additional work needed?

**Comment by mattpollock** [comment]
I _think_ that it would be difficult to get this for free. Syntax looks more like java lambda functions (e.g., https://docs.azuredatabricks.net/delta/data-transformation/higher-order-lambda-functions.html#higher-order-functions-tutorial-python).

So the SQL looks like
```sql
SELECT  key,
        values,
        TRANSFORM(values, value -> value + key) AS values_plus_key
FROM    nested_data
```

It would be really nice if the R call looked like using `purrr::map` (though `map` is an overloaded term here, which is why they named it `transform` in spark sql)
```r
nested_data %>%
  select(key, values) %>%
  mutate(values_plus_key = transform(values,  ~ .x + key))
```

Obviously this would take a little work to take `transform(values,  ~ .x + key)` and make it come out right. I'm not familiar with the `dbplyr` translation stuff - so I don't know how hard that is. Perhaps a path of less resistance would be to do something like
```r
nested_data %>%
  select(key, values) %>%
  hof_transform(output_col = values_plus_key, lambda = "value -> value + key")
```

Where `hof_*` functions are for "higher order functions". `sfd_*` probably doesn't work here because I haven't been able to find `transform()` in the java API. As far as I can tell it is a SQL feature.

**Comment by mattpollock** [comment]
https://databricks.com/session/an-introduction-to-higher-order-functions-in-spark-sql starting at about 15:30 explains it nicely

**Comment by mattpollock** [comment]
In the meantime, it is possible to use this stuff by means of the `ft_sql_transformer`, but it is awkward

Here's an example using the `FILTER` function
```r
library(sparklyr)
library(sparklyr.nested)
library(dplyr)
sc <- spark_connect(...)

# get some nested data
iris2 <- copy_to(sc, iris, name="iris", overwrite = TRUE)
iris_nst <- iris2 %>%
  sdf_nest(Sepal_Length, Sepal_Width, Petal_Length, Petal_Width, .key="data") %>%
  group_by(Species) %>%
  summarize(data=collect_list(data))

iris_filtered <- iris_nst %>% 
  ft_sql_transformer("
    SELECT Species,
           data,
           FILTER(data, datum -> datum.Sepal_Length < 5) AS filtered_data
    FROM   __THIS__")

head(iris_filtered)
# # Source: spark<?> [?? x 3]
#   Species    data        filtered_data
#   <chr>      <list>      <list>       
# 1 virginica  <list [50]> <list [1]>   
# 2 versicolor <list [50]> <list [1]>   
# 3 setosa     <list [50]> <list [20]>  
```

**Comment by geoHeil** [comment]
But:
```
library(nycflights13)
flights <- copy_to(spark, flights, "flights")

delayPerCarrier <- flights %>%
    group_by(carrier) %>%
  summarise(mean_dep_delay = mean(dep_delay), 
            data=sort_collect_set(dep_delay))

delayPerCarrier %>% 
  ft_sql_transformer("
    SELECT carrier,
           mean_dep_delay,
           data,
           TRANSFORM(data, element -> element +1) AS data_plus,
           FILTER(data, element -> element <5) AS filtered_data
    FROM   __THIS__")
```

Results in:
<img width="554" alt="__development_curriculae_UII-R-BigData_course-content_-_master_-_RStudio" src="https://user-images.githubusercontent.com/1694964/55853466-97e78a80-5b61-11e9-89a6-1c64b8e8a034.png">
which does not seem to be correct. I.e. the filter produces some other (random?) results as well as the plus operation does not change the data.

**Comment by mattpollock** [comment]
I'm not following here. Haven't run your code, but I expect that the values in `data_plus` are one unit greater than those in `data`, and of the 312 entries for carrier `WN` only 18 of them had a value less than 5

**Comment by benmwhite** [comment]
@geoHeil The Spark SQL filter call [is supposed to remove elements within the lists/arrays that don't match the statement in the predicate](https://spark.apache.org/docs/latest/api/sql/index.html#filter). If you're trying to get a logical list/array for each row with the exact same number of elements as the originals then you should try [transform](https://spark.apache.org/docs/latest/api/sql/index.html#transform) instead.

**Comment by geoHeil** [comment]
@benmwhite thanks I thought about it more like a Scala collection filter (inclusive, keep) predicate and not filterNot, more like a `WHERE` clause.  Thanks.

Regarding the `+1 ` operation - How can I print the elements? Coming from a scala background, I thought it behave like `df.show`, i.e. print the first characters even for nested elements.

**Comment by mattpollock** [comment]
```
library(sparklyr.nested)
delayPerCarrierTransformed %>% sdf_explode(data_plus)
```
is one option

**Comment by geoHeil** [comment]
But that would explode the data, i.e. generate large shuffle IO. If I just want to see the contents of the first 20 lines like `df.show` but including the nested objects is there no other way?

**Comment by mattpollock** [comment]
@yl790 do you think something along the lines of https://github.com/sparklyr/sparklyr/issues/1773#issuecomment-477992944 would be feasible in the near future? This seems to dovetail nicely with other nested-data work you've been doing.

**Comment by yl790** [comment]
@mattpollock I hope so :) It's definitely something to consider for sparklyr 1.3

**Comment by yl790** [comment]
@mattpollock @geoHeil Continuing with the iris example above, I found is a slightly better way to use both `dplyr` and Spark SQL higher-order functions without writing massive SQL queries:

```
library(sparklyr)
library(sparklyr.nested)
library(dplyr)

sc <- spark_connect(master = "local")
sdf <- copy_to(sc, iris, name = "iris", overwrite = TRUE)
sdf_nst <- sdf %>%
  sdf_nest(Sepal_Length, Sepal_Width, Petal_Length, Petal_Width, .key="data") %>%
  group_by(Species) %>%
  summarize(data=collect_list(data))

# create an example dplyr query that will apply some Apache Spark built-in function 
query <- sdf_nst %>%
         mutate(data = sql("filter(data, x -> x.Sepal_Length > 5)"))

# sanity-check the resulting SQL generated by dplyr is OK
show_query(query)

# now run the query
res <- query %>% sdf_collect()
```
So the trick is to pass the higher-order function you want to apply as `dplyr::sql("<HOF>")` to ensure it stays intact after everything else is translated to SQL.

This is a bit non-ideal though because you would need to ensure anything that's inside `dplyr::sql` is quoted/escaped properly and will not have SQL injection problems.

A solution that is even better than the slightly better solution above is probably to create some wrapper method in sparklyr that allows any lambda variable(s) and lambda body to separately be passed to `dbplyr::translate_sql` first which will perform necessary quotation and escapes, and then pass the quoted and escaped result into `mutate(data = sql(...))` as shown above.

**Comment by mattpollock** [comment]
Thanks for the `sql()` tip. I agree that it would be better to support some wrapper functions though. Appreciate that you are looking into this!
