### ISSUE TITLE
spark_connect() requires version argument even for non-local connections

### ISSUE THREAD

**Issue by dlindelof** [sparklyr/sparklyr#1827]
The documentation for `spark_connect()` states that the `version` argument is

> The version of Spark to use. Only applicable to "local" Spark connections.

But when I run on a YARN cluster I get the following error message:

> App > Error in spark_version_from_home(spark_home, default = spark_version) :
> App > Failed to detect version from SPARK_HOME or SPARK_HOME_VERSION. Try passing the spark version explicitly.

And from the discussion in https://github.com/rstudio/sparklyr/issues/1790 I get the feeling that the `version` argument is required even for non-local connections.

Is the documentation incorrect?

**Comment by javierluraschi** [comment]
@dlindelof which version of `sparklyr` are you using? There was indeed an issue that required this version to be set in some systems. It is our intention to have the version be auto-detected.

**Comment by yitao-li** [comment]
I think this is fixed by now. You can pass in `master = "yarn", spark_home = ...` and `sparklyr` will take care of the rest (well, at least that's definitely the case on Amazon EMR and Azure HDInsight anyways). `sparklyr` just needs something that allows it to determine which version of Spark it is working with. Feel free to re-open this issue if you find that's not the case on the Spark cluster you are working with.
