### ISSUE TITLE
Feature_Request: Write to Rds

### ISSUE THREAD

**Issue by jeereddys** [sparklyr/sparklyr#1834]
Write to R dataset directly from sparklyr without loading the dataframe to local memory.
spark_write_rds()

**Comment by benmwhite** [comment]
Spark writes out the data in its partitioned structure for fault tolerance, and the `spark_write_*` family are just wrappers for Spark's methods to the best of my knowledge. 

I don't think what you're requesting is possible, but one of the repo contributors on the RStudio team might be able to explain it better than I can.

**Comment by javierluraschi** [comment]
@jeereddys I guess the first question would be ask why do you want to write data as RDS files?

**Comment by jwjxz** [comment]
@javierluraschi I am in a situtation where I use SparklyR to clean up data from multiple sources and merge them into one common dataset for other analysts in the lab. Because not all other analysts are familiar with Spark or Sparklyr, so I need to write the data into a generic RDS or RData file so they can import the data into R directly and start straight with their analytic work.

**Comment by yitao-li** [comment]
@jwjxz There was a recent rewrite of `sparklyr` serialization routines that now works with a limited subset of RDS format version 2. I think we can change the same code path slightly into something that writes RDS format as well.

**Comment by yitao-li** [comment]
@jwjxz but you probably need to describe the scale of the data you are working with and also whether you need to collect all data to the driver node before writing everything to RDS or whether worker nodes should be writing to separate RDS files in parallel. If collecting all data back to the driver node then we would be limited by the memory available in the driver node.

**Comment by yitao-li** [comment]
@jwjxz Also, why not simply call `sdf_collect` on the post-processed spark dataframes? Is there any issue related to performance or memory limitation that prevents `sdf_collect` from succeeding? Typically `sdf_collect` is called to pull data from Spark back to R.

**Comment by jwjxz** [comment]
> @jwjxz Also, why not simply call `sdf_collect` on the post-processed spark dataframes? Is there any issue related to performance or memory limitation that prevents `sdf_collect` from succeeding? Typically `sdf_collect` is called to pull data from Spark back to R.

@yitao-li This is exactly what I am currently doing. I use 'collect' to pull spark dataframe to the driver's local R memory, then use 'saveRDS' to export to a file to share with my colleagues. Memory limitation is definitely an issue, but I usually cache the file in Spark and make sure the size of data does not exceed the driver's memory before running 'collect', so it can be somewhat avoided. Then, there is performance issue due to this extra step. Also, when using 'collect', R console can still be running for an extended period of time after the jobs on Spark have been completed. So, sometimes it is hard to tell whether the writing process has failed or I should just keep waiting for R to respond.
