### ISSUE TITLE
Not detecting already installed VC++ Redistributable 2015 

### ISSUE THREAD

**Issue by agrawalankita03** [sparklyr/sparklyr#1842]
# Reporting an Issue with sparklyr

---

VC++ 2015 is installed on my machine but I am still getting the below error 

Using spark 2.3.2
Error: Running Spark on Windows requires the Microsoft Visual C++ 2010 SP1 Redistributable Package. Please download and install from: 

  https://www.microsoft.com/download/en/details.aspx?id=13523

Restart your rsession after installation completes

```r
spark_version <- "2.3.2"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```

**Comment by yitao-li** [comment]
The error message was emitted because `sparklyr` could not locate `msvcr100.dll` using the following:

```
  systemRoot <- Sys.getenv("SystemRoot")
  systemDir <- ifelse(is_win64(), ifelse(is_wow64(), "sysnative", "system32"), "system32")
  msvcr100Path <- normalizePath(file.path(systemRoot, systemDir, "msvcr100.dll"),
    winslash = "/", mustWork = FALSE
  )
  haveMsvcr100 <- file.exists(msvcr100Path)
```

If everything else fails, you should consider installing Spark manually (e.g., see https://medium.com/@GalarnykMichael/install-spark-on-windows-pyspark-4498a5d8d66c) and then run `sc <- spark_connect(master = "local", spark_home = "<spark_home>")`
