### ISSUE TITLE
Collecting 1M rows several times triggers an exception in some environments

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#192]
Collecting 1M+ records several times triggers an exception in some environments; worth investigating this further at some point.

```
pickup_dropoff <- collect(pickup_dropoff_tbl)
Error in invoke_method.spark_shell_connection(sc, TRUE, class, method,  : 
  No status is returned. Spark R backend might have failed.
```

More more info on this one contact @nwstephens

**Comment by AlexIoannides** [comment]
I'm seeing exactly the same issue at precisely the same order of magnitude.

**Comment by yarrick19** [comment]
@javierluraschi 

I'm running into this issue as well using AWS EMR when attempting to `collect()` a large amount of data (~30M rows).  Any updates on the resolution of this issue?

**Comment by kevinushey** [comment]
We might need to do some chunked reading of data here -- e.g. read the data in 1M rows at a time. (Not yet sure if there's a natural way of doing this in Spark)

**Comment by edgararuiz** [comment]
Hi again @yarrick19 , I'm just curios about the reason why so many records need to be off-loaded from Spark and into R memory, can you share with me your use case?

**Comment by yarrick19** [comment]
Hi @edgararuiz .  First off, I'm working with very large volumes of data which is why I gravitated towards Spark.  At this point, I'm primarily using it for classification problems.  When scoring a data set using `sdf_predict`, I'm primarily interested in the probability of a case being in a class.  `sdf_+predict` returns this in the `probability` field, but that field needs to be parsed (see #176).    To do that, I'm attempting to `collect()` the data and parse it in R.  Is there an alternative?  I couldn't find a way to parse that field in Spark.

**Comment by edgararuiz** [comment]
Thanks @yarrick19 for the background, and thank you @kevinushey for your response for this on the other issue thread. 

In the meanwhile, @yarrick19 , did you get the same issue when using sdf_read_column?

**Comment by yarrick19** [comment]
@edgararuiz `sdf_read_column` won't work for me... I need the probability field along with two others and sdf_read_column only returns one row.

**Comment by edgararuiz** [comment]
Makes sense, I figured you tried it so I wondering what the limitation is.  Thanks!

**Comment by DerekYves** [comment]
Just wanted to add that I'm seeing this issue too at around the same order of magnitude. My source data set is into the billions so extracting 1m is really a very small sample but I'm running into this error quite a lot during the collect phase. Wondered if any additional info was available? I have EMR 5.3 and the github version of sparklyr installed.

Thanks!

**Comment by dkincaid** [comment]
I get this error just trying to collect() about 1000 rows of data from Spark to R. In fact, almost every time I try to collect any data to sparklyr I get this. I have `spark.driver.memory` set to 30g thinking maybe it was running out of memory. But the 1000 rows of data each only have one string that is less than 20 characters long, so there is no way it's running out of memory. The backend of sparklyr seems very unstable. It crashes frequently.

**Comment by edgararuiz** [comment]
@DerekYves / @dkincaid - Maybe it isn't the `collect()` phase that is causing the issue.  Maybe it is something that happens before during data transformation, but it doesn't error out because the entire piped expression is lazily evaluated.  Can we try registering and caching the statement first (`sdf_register` & `tbl_cache`)? And then perform `collect()`?

**Comment by dkincaid** [comment]
It is already being done after both `sdf_register` and `tbl_cache`

**Comment by dkincaid** [comment]
Is there anything I can do to help troubleshoot this? My only workaround right now is to use spark_write_csv() to write the data to a file and then use readr::read_csv to read it into local R. Pretty kludgy and a real pain.

**Comment by randomgambit** [comment]
same problem here.. @dkincaid how do you read back your csv generated by spark_read_csv? I obtain a folder with many many files instead of a classical csv...

**Comment by dkincaid** [comment]
Use `sdf_repartition(mySparkDataFrame, 1)` to make it output a single file.

**Comment by randomgambit** [comment]
thanks, I am trying right now. actually not a bad solution at all. writing seems to be suuuuper slow

**Comment by randomgambit** [comment]
@dkincaid is it usually very slow? I see the corresponding folder has been created, but it only contains some _temporary file while sparklyr is still running forever...

**Comment by chandramaloo** [comment]
Any progress on this issue? I am facing this problem even with around 1000 rows (<1MB data).

**Comment by chandramaloo** [comment]
@dkincaid you said the problem has been solved for you. Which version are you currently using?

**Comment by yitao-li** [comment]
Please see https://github.com/sparklyr/sparklyr/pull/2910 plus the explanation below for something that may help when it comes to collecting large amount of data from Spark to R. This change is not in CRAN yet but is in the master branch of Sparklyr.

Assuming you are running Spark in distributed mode, then for very large data, ensuring the dataframe is partitioned evenly and then calling `spark_write_rds()` to write each partition to a separate RDS file and calling `collect_from_rds()` on the individual RDS files to load them into R dataframes may be the way to go. When Spark is running in distributed mode, `spark_write_rds()` will tell Spark workers to write each partition into a RDS file in HDFS. After you download such files from HDFS to local filesystem, you can then call `collect_from_rds()` on each of the local copies of those files to deserialize data into R dataframes.

Reason why I think it would help: `spark_write_rds()` processes data within each partition within worker nodes rather than sending all of them back to the driver node. Assuming you don't have overly large partition that causes a worker node to run out of memory, then it will work as expected.
