### ISSUE TITLE
How to count NA Values?

### ISSUE THREAD

**Issue by leYiRaMa** [sparklyr/sparklyr#1960]
Is this even supported? I've looked everywhere and can't find a way to do what is an extremely common task for working with data.

Any help is appreciated.

**Comment by benmwhite** [comment]
If you want the number of NAs in a single column you can filter down and follow it with a row count:
```
spark_tbl %>%
  filter(is.na(column_of_interest)) %>%
  sdf_nrow()
```

**Comment by filipwastberg** [comment]
Is there a strategy for counting NA in all columns?

**Comment by benmwhite** [comment]
Normally you should be able to use `summarise_all()`, but [there are some issues with that family of dbplyr functions that are being resolved right now](https://github.com/rstudio/sparklyr/issues/2050).

Once everything's working as expected you should be able to run something like the following:

```
spark_tbl %>%
  summarise_all(~sum(as.integer(is.na(.))))
```

You'd need the `as.integer()` in there since Spark doesn't convert logical values to numeric implicitly like with base R `sum()` or `mean()`.

For now you can do something like the following workaround: 

```
library(purrr)
library(rlang)

iris_tbl <- sdf_copy_to(sc, iris)
column_names <- colnames(iris_tbl)

map(
  column_names,
  function(x) {
    x_sym <- sym(x)
    summarise(iris_tbl, !!x_sym := sum(as.integer(is.na(!!x_sym))))
  }
) %>% sdf_bind_cols()
``` 

```
# Source: spark<?> [?? x 5]
  Sepal_Length Sepal_Width Petal_Length Petal_Width Species
         <dbl>       <dbl>        <dbl>       <dbl>   <dbl>
1            0           0            0           0       0
```

(There's probably a better way, and I fully expect the tidy eval police to knock down my door for posting this)

**Comment by filipwastberg** [comment]
Haha! 

Yeah, that's pretty much how I solved it as well.

Seems like this shouldn't be to hard to implement as a new `sdf_` function?

**Comment by filipwastberg** [comment]
Or perhaps this should be included in `sdf_describe()`?

**Comment by lucasmation** [comment]
I tryed @benmwhite's solution on a character column and got the this error:

```
cnis_pf %>% filter(is.na(DT_NASCIMENTO)) %>% sdf_nrow()
Error in storage.mode(x) <- "double" : 
  (list) object cannot be coerced to type 'double'
```
Should the above code have worked for character columns? Is there any other way that works?

**Comment by benmwhite** [comment]
Double check the column, it looks like it might actually be array-valued rather than character-valued.

**Comment by ecoelhor** [comment]
> Normally you should be able to use `summarise_all()`, but [there are some issues with that family of dbplyr functions that are being resolved right now](https://github.com/rstudio/sparklyr/issues/2050).
> 
> Once everything's working as expected you should be able to run something like the following:
> 
> ```
> spark_tbl %>%
>   summarise_all(~sum(as.integer(is.na(.))))
> ```
> 
> You'd need the `as.integer()` in there since Spark doesn't convert logical values to numeric implicitly like with base R `sum()` or `mean()`.
> 
> For now you can do something like the following workaround:
> 
> ```
> library(purrr)
> library(rlang)
> 
> iris_tbl <- sdf_copy_to(sc, iris)
> 
> sdf_count_nas <- function(spark_tbl) {
>   column_names <- colnames(spark_tbl) 
>   map(
>     column_names,
>     function(x) {
>       x_sym <- sym(x)
>       summarise(spark_tbl, !!x_sym := sum(as.integer(is.na(!!x_sym)), na.rm = TRUE))
>     }
>   ) %>% sdf_bind_cols()
> }
> 
> sdf_count_nas(iris_tbl)
> ```
> 
> ```
> # Source: spark<?> [?? x 5]
>   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
>          <dbl>       <dbl>        <dbl>       <dbl>   <dbl>
> 1            0           0            0           0       0
> ```
> 
> (There's probably a better way, and I fully expect the tidy eval police to knock down my door for posting this)

This is currently working.

```
spark_tbl %>%
  summarise_all(~sum(as.integer(is.na(.))))
```

**Comment by benmwhite** [comment]
@ecoelhor I believe the recent dbplyr update also added support for using `across()` within `summarise()` too, the goal being to deprecate the `*_all()`, `*_if()`, and `*_at()` versions of `summarise()` and `mutate()`. 

I haven't had a chance to do any testing, but since sparklyr uses dbplyr SQL translation I'd imagine it should work in Spark as well.

**Comment by ecoelhor** [comment]
@benmwhite Thank you for the comment. I didn't notice the ![](https://dplyr.tidyverse.org/reference/figures/lifecycle-superseded.svg) before.
