### ISSUE TITLE
Unable to understand spark_apply

### ISSUE THREAD

**Issue by Scotturbina** [sparklyr/sparklyr#1990]
Hello guys,

I am developing a ML model in R and I am trying to use SparklyR for move it into production, I am having problems right now doing some feature engineering and I do not know how to use spark_apply function:

I got this variable
`test_query<-sdf_sql(Connection,"Query")`

Then I need to do this feature engineering: 

```
preprocessing<-function(datasetml){


datasetml$Name_has_numbers<-grepl("[[:digit:]]" , datasetml$NAME_NORM_LONG)


datasetml$Num_words_name<-stri_count_words(datasetml$NAME_NORM_LONG)


datasetml$Num_char_w1<-nchar(word(datasetml$NAME_NORM_LONG,1))


datasetml$Num_char_w2<-nchar(word(datasetml$NAME_NORM_LONG,2))

return(datasetml)
}
```

How can I apply this function with spark_apply to my sdf variable named test_query?

```
spark_version <- "2.3.0"
sc <- spark_connect(master = "yarn-client", version = spark_version)
```

**Comment by benmwhite** [comment]
`spark_apply()` ships your data and required R packages out to every executor, runs your code through through R on your individual partitions, then puts it all back together in a Spark table. If you're only doing feature engineering then this adds way too much unnecessary overhead. Instead, you should use`sparklyr::ft_*` [functions](https://cran.r-project.org/web/packages/sparklyr/sparklyr.pdf) and/or dplyr verbs with [Spark SQL functions](https://spark.apache.org/docs/latest/api/sql/index.html) inside them whenever possible since you avoid transferring data and code between Spark and local worker node R instances. 

That said, your `spark_apply()` code is failing because every external package you use in your function needs to be declared explicitly. Change `word()` to `stringr::word()`, etc.

**Comment by Scotturbina** [comment]
@benmwhite  And can I combine Spark SQL function with an R function?

**Comment by benmwhite** [comment]
Only inside dplyr verbs like `mutate()`, `summarise()`, etc. If they receive a Spark table as input then they take the expressions inside them and translate the operation chain to Spark SQL under the hood.
