### ISSUE TITLE
How to extract hour from timestamp in sparklyr?

### ISSUE THREAD

**Issue by yogi-srcc-iimb** [sparklyr/sparklyr#2006]
Find the below example for reproducible purpose. My dataframe is df and I am trying to get local hour from newly created column "local_time" . I am facing issues when I try to get local_hour from local_date . Not sure what is wrong.

# Reporting an Issue with sparklyr

df<-data.frame(utc_time_stamp=c("2019-04-28 18:35:26","2019-04-28 21:28:58","2019-04-28 18:59:01"),time_zone=c("Asia/Tokyo","Australia/Brisbane","Etc/GMT-12"))

#loading data into spark

df1<-copy_to(sc,df,"df1",overwrite = T)

# creating local time using time zone from UTC time stamps

df2 <- df1 %>%
group_by(time_zone) %>%
mutate(local_time = from_utc_timestamp(timestamp(utc_time_stamp) ,time_zone))

# Extracting hour from local time column

df3 <- df2 %>%
group_by(time_zone) %>%
mutate(local_hour = hour(timestamp(local_time)))

df3

This is the error I get when i execute code related to hour extraction

  Error: org.apache.spark.sql.catalyst.parser.ParseException: 
missing ')' at 'FROM'(line 1, pos 65)

== SQL ==
SELECT `utc_time_stamp`, `time_zone`, `local_time`, EXTRACT(hour FROM timestamp(`local_time`)) AS `local_hour`
-----------------------------------------------------------------^^^
FROM (SELECT `utc_time_stamp`, `time_zone`, 
from_utc_timestamp(timestamp(`utc_time_stamp`), `time_zone`) AS `local_time`
FROM `df1`) `dbplyr_190`

**Comment by benmwhite** [comment]
It looks like the `group_by()` call messes with the SQL parsing. In this case you shouldn't be grouping anyway since the operations are performed over each element. The following code works for converting the time stamps and extracting the local hour as an integer:

```
df1 %>% 
  mutate(
    local_time = from_utc_timestamp(utc_time_stamp, time_zone), 
    local_hour = hour(local_time)
  )
```

```
# Source: spark<?> [?? x 4]
  utc_time_stamp      time_zone          local_time          local_hour
  <chr>               <chr>              <dttm>                   <int>
1 2019-04-28 18:35:26 Asia/Tokyo         2019-04-29 03:35:26          3
2 2019-04-28 21:28:58 Australia/Brisbane 2019-04-29 07:28:58          7
3 2019-04-28 18:59:01 Etc/GMT-12         2019-04-29 06:59:01          6
```

Also a minor point, but after getting to test it out it looks like `from_utc_timestamp()` can convert directly from characters without the intermediate `timestamp()` step.

**Comment by yogi-srcc-iimb** [comment]
I tried the suggested solution , it shows an error (I am using Windows machine , this solution seems to be working when I run the same script in Mac OS ) I guess it is something to do with OS settings ...

Anyway this is what I get when I execute the code.

> df1 %>% 
+   mutate(
+     local_time = from_utc_timestamp(start_time, time_zone), 
+     local_hour = hour(local_time)
+   )
Error in paste0(args[[1]], " ", fun, " ", args[[2]]) : 
  cannot coerce type 'closure' to vector of type 'character'


I have examined my code line by line , and I noticed that it is caused by hour function only inside mutate .  I am able to create local time column separately without any issue , issue arises when I try to calculate local hour .... Just see my code below ...

## Here , I am able to create local_time column successfully 
df1 %>%
  group_by(time_zone) %>%
  mutate(local_time = from_utc_timestamp(timestamp(utc_time_stamp) ,time_zone))


## This query fails , so I guess it is to do with hour function issue ...
df1 %>%
  mutate(new_local_hour = hour(timestamp(local_time)))

Error: org.apache.spark.sql.catalyst.parser.ParseException: 
missing ')' at 'FROM'(line 1, pos 161)

**Comment by sdanielzafar** [comment]
We are currently facing this issue as well, not able to use the `hour` function. Any ideas/updated?

**Comment by robin-loche** [comment]
I've had this issue since I updated my packages not long ago. I found the problem, I think it's from an [update in dbplyr 1.4.0](https://dbplyr.tidyverse.org/news/index.html#dbplyr-1-4-0) in the SQL translation part: it handle differently some lubridate functions like hour, year, ...
Even if lubridate is not loaded, I still have this issue.
The workaround I found is to use the sql() function to avoid the translation of this functions by dplyr in the `EXTRACT(hour FROM` form, and directly use the hive sql functions (functions that you can find for example [here](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF)). The working version for me looks like this (start is my timestamp field):
`df_spark %>% mutate(
      start_year = sql("year(from_unixtime(`start`))")
)`

**Comment by robin-loche** [comment]
The corresponding issue is now open : #2140
