### ISSUE TITLE
Strings with "NA" still handled incorrectly in sdf_copy_to

### ISSUE THREAD

**Issue by caewok** [sparklyr/sparklyr#2031]
Problem: 

When copying a data frame into spark, sdf_copy_to (or spark?) is treating characters or factors that use "NA" as NA. At least in R, "NA" is not the same as NA. Thus the copy in spark may have more NAs than it should. 

This appears related to https://github.com/rstudio/sparklyr/pull/1854. 

Example:
```r
sc <- spark_connect()

na_dat <- data.frame(A = rep("NA", times = 10),
                     B = c(rep("NA", times =5), rep(NA, times = 5)),
                     C = c(rep("C", times = 5), rep("NA", times = 3), rep(NA, times = 2)),
                     stringsAsFactors = FALSE)
na_dat_spark <- sdf_copy_to(sc = sc, x = na_dat, name = "na_dat", 
                          repartition = 8)
na_dat # A has zero NAs; B has 50% NAs; C has 20% NAs.
na_dat_spark # A and B are all NAs; C is 50% NAs
```

**Comment by jablauvelt** [comment]
Just wanted to say, facing the same issue, and it doesn't seem like there are any args that can affect this.

**Comment by wkdavis** [comment]
The way that the data is written to Spark, it is first written to a temporary CSV and then written to Spark.

https://github.com/sparklyr/sparklyr/blob/f82d3c04d34db6596299f847c156786036227884/R/data_copy.R#L167

https://github.com/sparklyr/sparklyr/blob/f82d3c04d34db6596299f847c156786036227884/java/spark-1.5.2/utils.scala#L270-L304

After the CSV write, any `NA` become `"NA"`, so when the scala method reads and parses the CSV file it looks for `"NA"` to set as `null` (the Spark version of `NA`). This would also scoop up any values that are `"NA"` in R prior to the CSV creation, because after the data is written to the CSV both `NA` and `"NA"` will become `"NA"`. I think the only way around your issue would be to use some other value besides `"NA"` if you wan to distinguish between R's `NA` and `NA` in your dataset.

**Comment by yitao-li** [comment]
@wkdavis I'm in the process of replacing serialization code paths involving CSV with something more sensible in https://github.com/sparklyr/sparklyr/pull/2757

**Comment by yitao-li** [comment]
@caewok Actually the `"NA"` strings are preserved as character vectors correctly, both before and after the change in #2757 

I think one source of confusion is how the data is displayed from the Spark data frame, e.g.,

```
# Source: spark<?> [?? x 1]
   x    
   <chr>
 1 NA   
 2 NA   

```

Notice if the type of column `x` is <chr>, then the entire column is of type string (which you can also verify with `sdf %>% sdf_schema()`)

**Comment by yitao-li** [comment]
@caewok @wkdavis This is fixed now after an extensive rewrite (!) of serialization routines in https://github.com/sparklyr/sparklyr/pull/2757 :slightly_smiling_face:
