### ISSUE TITLE
Sparklyr 1.0.5 don't see hive tables and databases

### ISSUE THREAD

**Issue by ucoque** [sparklyr/sparklyr#2202]
Today after updating to 1.0.5 and start a spark session from Rstudio, I was not able to see any tables or databases. 

my way to connect to the cluster is:

spark.conn <- function(){
  conf <- spark_config()
  sc <- spark_connect(master = "yarn-client",
                      spark_home = "/usr/hdp/current/spark2-client/",
                      config = conf,
                      app_name = "Sparklyr wn0")
  
  return(sc)
}
sc <- spark.conn()

As you can see it has nothing special, but I have moved back to 1.0.4 and see tables again.

**Comment by FBullier** [comment]
Same problem here, it works in 1.0.4 and fails in 1.05 ie src_databases() returns only Default

**Comment by tusharmajhi9** [comment]
+1 Facing exactly the same issue.

**Comment by javierluraschi** [comment]
Probably can be fixed with:

```
config$spark.sql.catalogImplementation <- "hive"
```

@ucoque @FBullier @tusharmajhi9: If you connect with the spark-shell, pyspark, etc. do you see the Hive tables without having to use additional configuration parameters? My guess is that these tables won't be visible anyways, but I might be wrong here, so any additional information would be helpful. For instance, what cluster provider are you using? Which version of Hadoop? Which version of Spark, etc.

Some more background: `sparklyr 1.0.4` used to overwrite `config$spark.sql.catalogImplementation <- "hive"` in all configs; however, that broke other users, so we are trying to avoid overriding settings. If we can convince ourselves that this change is needed, we can bring it back in `sparklyr 1.0.6`, that said, it is usually preferred to not override making `sparklyr` override user settings.

**Comment by ucoque** [comment]
Hi @javierluraschi 

I've not tried pyspark or spark-shell so i don't really know. However, in my case, I'm using and Microsoft hdinsight  cluster, haddop version 2.6.2.38-1 and spark 2.1.1.2.6.2.38-1.

And anyway, I have added config$spark.sql.catalogImplementation <- "hive" to mi configuration and it works.

**Comment by javierluraschi** [comment]
Thank you, @ucoque.

@FBullier @tusharmajhi9 are you also using Microsoft hdinsight?

Thanks!

**Comment by tusharmajhi9** [comment]
@javierluraschi I am using Hortonworks, any known issues with that?

**Comment by Hyurt** [comment]
Any news about it ? 

Using AWS with EMRs and Glue Data Catalog for hive, we faced the same problem since 1.0.5 - downgrading to 1.0.4 is a fix, but we'd prefer be able to upgrade dependancies (eg: some versions of h2o can be blocking)

Will it be corected in future release ? If yes, do you know when ?


Thanks

**Comment by rychien-official** [comment]
Hey @javierluraschi , would just like to say I also encounter this issue using sparklyr v1.1. Rolling back to sparklyr v1.0.4 solves the problem. My environment is RStudio Server 1.2.5033, R 3.6.3, Spark 2.3.1, Hadoop 3.0.1, and I work on a private cluster.

Thanks in advance!

-Ryan
