### ISSUE TITLE
[Question]: How do I filter a stream such that only the last 5 entries are kept

### ISSUE THREAD

**Issue by fabiangehring** [sparklyr/sparklyr#2223]
Hi,

I have an input stream that sends quite a lot of data. Since I'm only interested in the last 100 entries I'd like to get rid of all the rest.

My approach is as follows:
`
input_stream <- stream_read_scoket(sc, options = list(host = "localhost", port = 9997L))
output_stream <- stream %>% stream_watermark() %>% stream_write_memory(name = "last_100_only")
`

But non of the following filters seems to work:

# top_n
`
input_stream <- stream_read_scoket(sc, options = list(host = "localhost", port = 9997L))
output_stream <- stream %>% stream_watermark() %>% top_n(100, timestamp) %>% stream_write_memory(name = "last_100_only")
`

# arrange and head
`
input_stream <- stream_read_scoket(sc, options = list(host = "localhost", port = 9997L))
output_stream <- stream %>% stream_watermark() %>% arrange(desc(timestamp)) %> head(100) %>% stream_write_memory(name = "last_100_only")
`

How do I filter an incoming stream, such that not all input is kept?

**Comment by yl790** [comment]
I don't think with spark streaming you can ever have an output _stream_ that also works like a circular buffer -- because stream is by definition append-only and there is no support for discarding all records prior to a certain record within a stream.

However, one can definitely implement a foreach sink in java / scala that, say, stores the current row somewhere, and then discards anything before the last 100 rows, but this is not supported in R yet.
