### ISSUE TITLE
copy_to spark failed with arabic text column.

### ISSUE THREAD

**Issue by uttamraj9** [sparklyr/sparklyr#2227]
I am fetching twieets from twitter api and loading the data into hive using sparklyr, Problem I am facing with arabic text. In hive text are displaying in non readable format for arabic text.
eg: @TomeiTech @HCT_UAE \u0627\u0644\u0644\u0647 \u064a\u0628\u0627\u0627\u0627\u0627\u0631\u0643 \u0641\u064a\u064a\u064a\u064a\u062c \U0001f62d\u2764\ufe0f\u2764\ufe0f

So I added "Sys.setlocale("LC_ALL", "en_US.UTF-8")" In my R scripts now it displaying arabic text from r cmd when I print:"@TomeiTech @HCT_UAE الله يباااارك فييييج \U0001f62d❤️❤️"

But loading data into sparklyr using copy_to gives this error from R CMD:
<simpleError: java.nio.charset.MalformedInputException: Input length = 1

I am surprised same code works with Rstudio perfectly, But I need to schedule the r script from Rcmd. Please help me fixing this issue here is my working code with Rstudio but not working with R cmd:
library(sparklyr)
library(rtweet)
## name assigned to created app
appname <- "RtSentiment"
## api key (example below is not a real key)
key <- "xxxxxx"
secret <- "xxxxxx"
access_token <- "xxxxxxxx"
access_secret <- "xxxxxxx"
twitter_token <-create_token(
  app = appname,
  consumer_key = key,
  access_token = access_token,
  access_secret = access_secret,
  consumer_secret = secret)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
hct_hnd_twt <- search_tweets(q = "HCT_UAE", n=3,type = "recent",until=Sys.Date())
##Use spark to load data in hive
Sys.setenv(SPARK_HOME = "/opt/cloudera/parcels/CDH/lib/spark")
system("export KRB5CCNAME=/tmp/krb5cc_infabdm_twitter")
system("kinit -p infabdm@AD.HCT.AC.AE -k -t /home/ruser/infabdm.keytab")
##Spark R config
config <- spark_config()
config$spark.executor.cores <- 10
config$spark.executor.memory <- "16G"
sc <- spark_connect(master = "yarn-client", config = config, version = '1.6.0')
hct_hnd_twt <- copy_to(sc, hct_hnd_twt, "hct_hnd_twt",overwrite = TRUE)
DBI::dbGetQuery(sc, "create table r_social_media.hct_handle_tweets_d STORED AS PARQUET as SELECT * FROM hct_hnd_twt")

**Comment by uttamraj9** [comment]
Without adding  Sys.setlocale("LC_ALL", "en_US.UTF-8") to script it works from R CMD but the arabic text  is in non readable format.

**Comment by yl790** [comment]
I think the aforementioned readability problem after Sys.setlocale("LC_ALL", "en_US.UTF-8") is more of a "presentation layer" issue that arises from the specific console / terminal / graphical user interface being used to view the data, in combination with the set of fonts they may or may not support that can display the characters correctly. It should definitely be addressed separately from data-related issues such as java.nio.charset.MalformedInputException when ingesting data into Spark. It sounds like the data-import problem is fixed by setting the correct locale. So, I'll close this issue now.
