### ISSUE TITLE
Kerberos ticket inside spark_apply function.

### ISSUE THREAD

**Issue by jaccoheres** [sparklyr/sparklyr#2238]
Is it possible to get my kerberos ticket inside an spark_apply loop? I would like to read data from impala/kudu after applying some R functionality to my input. Currently I am able to move the implyr package and the impala jdbc driver towards my spark-apply session, but not the kerberos ticket. I cannot find anywhere whether this is possible or not. If this is possible this would truly extend the possibilities of sparklyr, as one can combine data from multiple tables on the cluster without going forth and back from spark to R.
My code structure would look like this:
`
# kinit in terminal of RStudio
# start up spark session

result <- spark_apply(sc, df,
  function(x){
    library(implyr)
    #do some data manipulation using x using R functions

    #construct an impala query based on the outcomes of the data manipulation

   #Create impala connection named impala_con, currently this fails because I have no kerberos 
     ticket
   impala_data <- dbGetQuery(impala_con, query)
   
  #Do some further manipulations
  return(result)
  },
  packages = TRUE
)
`

Thanks for the help!

**Comment by yl790** [comment]
Hey @jaccoheres thanks for asking! :)

I don't think there is any "silver bullet" in sparklyr that can forward a kerberos ticket from one host to another.

First of all, kerberos tickets are by default  not forward-able from one host to another unless they are requested with "kinit -f" and the KDC decides a forward-able ticket can be granted.

Also, my take is managing distribution of credentials should be something done at the spark cluster provision time rather than at the sparklyr level at run time, as sparklyr is not really on the right level of the stack to handle kerberos-related matters.
