### ISSUE TITLE
"ft_one_hot_encoder_estimator()" doesn't work properly in "ml_pipeline()" 

### ISSUE THREAD

**Issue by panda-michiie** [sparklyr/sparklyr#2251]
Hi,
Now, I want to do feature engineering to some data (train_data), then I'm making pipeline by using ml_pipeline().

In my pipeline, I use ft_one_hot_encoder_estimator().
But, this function doesn't work properly in ml_pipeline() in sparklyr ver1.1.0 as below.

----- description of train_data -----
not_working  [dbl] 0, 0, 1, 0, 1, 0, 0,...
age                [int] 18, 28, 31, 15, 18, 17, 40,...
sex                 [chr] "m", "f", "m", "m", "f", "m", "f",...

-----R code1 (ml-pipeline) -----
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.4.3")
train_data <- spark_read_parquet(sc,"data/train_data.parquet")

#ml-pipeline
pipeline <- ml_pipeline(sc) %>% 
  ft_string_indexer(input_col = "sex",output_col = "sex_indexed") %>% 
  **ft_one_hot_encoder_estimator( 
    input_cols = c("sex_indexed"),
    output_cols = c("sex_encoded")
  )**
pipeline_model <- **ml_fit(pipeline,train_data)**
----- END -----

-----R code2 (directly applied) -----
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.4.3")
train_data <- spark_read_parquet(sc,"data/train_data.parquet")

#directly applied
data_train %>% 
  ft_string_indexer(input_col = "sex",output_col = "sex_indexed") %>% 
  **ft_one_hot_encoder_estimator( 
    input_cols = c("sex_indexed"),
    output_cols = c("sex_encoded")
  )**
----- END -----

I get error messages as below from R code1.
**error in as.character(call[[1]]): 
cannot coerce type 'closure' to vector of type 'character'**

However, when I apply those process to the data directly, I don't get any error messages (R code2) and successfully make encoded column "sex encoded".

**Comment by yl790** [comment]
Hey I think the actual problem was this feature is only supported in spark 3.0 and beyond. For some reason the error message was highly obscure and unhelpful though and is definitely worth fixing.

This is what I see after running through your example code, getting the same error message with spark 2.4.4, and then running `traceback()` after the error:

Error in as.character(call[[1]]) : 
  cannot coerce type 'closure' to vector of type 'character'
> traceback()
**21: spark_require_version(spark_connection(jobj), "3.0.0")**
20: (function (jobj) 
    {
        spark_require_version(spark_connection(jobj), "3.0.0")
        new_ml_transformer(jobj, category_size = invoke(jobj, "categorySize"), 
            class = "ml_one_hot_encoder_model")                                                                                                                                     
    })(jobj = <environment>)
19: do.call(ml_get_constructor(jobj), list(jobj = jobj))
18: FUN(X[[i]], ...)
17: lapply(stages, ml_call_constructor)
16: (function (jobj, ..., class = character()) 
    {
        stages <- tryCatch({
            jobj %>% invoke("stages")
        }, error = function(e) {
            NULL
        })
        if (!rlang::is_na(stages)) 
            stages <- lapply(stages, ml_call_constructor)
        new_ml_transformer(jobj, stages = stages, stage_uids = if (rlang::is_null(stages))                                                                                          
            NULL
        else sapply(stages, function(x) x$uid), ..., class = c(class, 
            "ml_pipeline_model"))
    })(jobj = <environment>)
15: do.call(ml_get_constructor(jobj), list(jobj = jobj))
14: ml_call_constructor(.)
13: function_list[[k]](value)
12: withVisible(function_list[[k]](value))
11: freduce(value, `_function_list`)
10: `_fseq`(`_lhs`)
9: eval(quote(`_fseq`(`_lhs`)), env, env)
8: eval(quote(`_fseq`(`_lhs`)), env, env)
7: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
6: spark_jobj(x) %>% invoke("fit", spark_dataframe(dataset)) %>% 
       ml_call_constructor()
5: ml_fit(pipeline, train_data) at repro.R#23
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))

**Comment by CooperChen453** [comment]
Even if i have installed the latest spark version(3.1.1), when i use ft_one_hot_encoder, it still returns error like this:
`error in as.character(call[[1]]):
cannot coerce type 'closure' to vector of type 'character'`.

And when i use traceback(), it returns something like this:
`11: spark_require_version(spark_connection(jobj), "3.0.0")
10: (function (jobj) 
    {
        spark_require_version(spark_connection(jobj), "3.0.0")
        new_ml_transformer(jobj, category_size = invoke(jobj, "categorySize"), 
            class = "ml_one_hot_encoder_model")
    })(jobj = <environment>)
9: do.call(ml_get_constructor(jobj), list(jobj = jobj))
8: FUN(X[[i]], ...)
7: lapply(stages, ml_call_constructor)
6: (function (jobj, ..., class = character()) 
   {
       stages <- tryCatch({
           jobj %>% invoke("stages")
       }, error = function(e) {
           NULL
       })
       if (!rlang::is_na(stages)) {
           stages <- lapply(stages, ml_call_constructor)
       }
       new_ml_transformer(jobj, stages = stages, stage_uids = if (rlang::is_null(stages)) {
           NULL
       }
       else {
           sapply(stages, function(x) {
               x$uid
           })
       }, ..., class = c(class, "ml_pipeline_model"))
   })(jobj = <environment>)
5: do.call(ml_get_constructor(jobj), list(jobj = jobj))
4: ml_call_constructor(.)
3: spark_jobj(x) %>% invoke("fit", spark_dataframe(dataset)) %>% 
       ml_call_constructor()
2: ml_fit(., train)
1: pipeline %>% ml_fit(train)`.

How weird it is.

I think that it is a bug, maybe?

**Comment by yitao-li** [comment]
@CooperChen453 Thanks for the feedback. I see the reason it was not working for Spark 3.0 was because of the breaking change mentioned in https://spark.apache.org/docs/latest/ml-migration-guide.html#breaking-changes

I'll work on fixing this one soon.

**Comment by CooperChen453** [comment]
> @CooperChen453 Thanks for the feedback. I see the reason it was not working for Spark 3.1 was because of the breaking change mentioned in https://spark.apache.org/docs/latest/ml-migration-guide.html#breaking-changes
> 
> I'll work on fixing this one soon.

OK, thank you very much.

**Comment by yitao-li** [comment]
@CooperChen453 @panda-michiie `OneHotEncoderEstimator` doesn't exist any more in Spark 3.0 or above. You should switch to `OneHotEncoder` instead (see https://spark.apache.org/docs/latest/ml-migration-guide.html#breaking-changes).

Because ML-related functions in `sparklyr` largely mirrors the MLlib class names in term of naming, this means you should switch from `sparklyr::ft_one_hot_encoder_estimator()` to `sparklyr::ft_one_hot_encoder()` for R code working exclusively with Spark 3.0 or above.

**Comment by CooperChen453** [comment]
> @CooperChen453 @panda-michiie `OneHotEncoderEstimator` doesn't exist any more in Spark 3.0 or above. You should switch to `OneHotEncoder` instead (please carefully examine https://spark.apache.org/docs/latest/ml-migration-guide.html#breaking-changes).
> 
> Because ML-related functions in `sparklyr` largely mirrors the MLlib class names in term of naming, this means you should switch from `sparklyr::ft_one_hot_encoder_estimator()` to `sparklyr::ft_one_hot_encoder()` for R code working exclusively with Spark 3.0 or above.
> 
> I think the only thing that needs to be fixed in `sparklyr` is the error message emitted when the outdated `ft_one_hot_encoder_estimator()` function is called when working with Spark 3.0+

OK, i get you. So i think whether or not it is proper to remove ft_one_hot_encoder_estimator() in the latest sparklyr in case that the users are confused when they want to use one hot encoding process.

And as mentioned above, the ft_one_hot_encoder() is not working correctly in the pipeline now. Look forward to your reply on this later. Thanks.

**Comment by CooperChen453** [comment]
> > @CooperChen453 @panda-michiie `OneHotEncoderEstimator` doesn't exist any more in Spark 3.0 or above. You should switch to `OneHotEncoder` instead (please carefully examine https://spark.apache.org/docs/latest/ml-migration-guide.html#breaking-changes).
> > Because ML-related functions in `sparklyr` largely mirrors the MLlib class names in term of naming, this means you should switch from `sparklyr::ft_one_hot_encoder_estimator()` to `sparklyr::ft_one_hot_encoder()` for R code working exclusively with Spark 3.0 or above.
> > I think the only thing that needs to be fixed in `sparklyr` is the error message emitted when the outdated `ft_one_hot_encoder_estimator()` function is called when working with Spark 3.0+
> 
> OK, i get you. So i think whether or not it is proper to remove ft_one_hot_encoder_estimator() in the latest sparklyr in case that the users are confused when they want to use one hot encoding process.
> 
> **And as mentioned above, the ft_one_hot_encoder() is also not working correctly in the pipeline with Spark 3.0+ now(It works correctly in Spark 2.4.7 as i try).** Look forward to your reply on this later. Thanks.

Since the ft_one_hot_encoder() can not work correctly in the pipeline with spark 3.0+, i transform to use spark 2.4.7 to use the onehot function and it works well. But another question is that i can only input one column to do the onehot transformation once i use one ft_one_hot_encoder(). In fact, in the original Spark, you can input many columns all at once in one OneHotEncoder function. It is not consistant with the ft_one_hot_encoder() in sparklyr. So can anyone solve it?

```
library(sparklyr)

sc <- spark_connect('local', version = '3.1.1')

cars <- sdf_copy_to(sc, mtcars)

pipeline <- ml_pipeline(sc) %>% 
  ft_one_hot_encoder(
    input_cols = c('cyl', 'am'),
    output_cols = c('cyl_encoded', 'am_encoded')
  )

pipeline %>% 
  ml_fit(
    cars
  )
```
It returns error like this:
```
Error in as.character(call[[1]]) : 
  cannot coerce type 'closure' to vector of type 'character'
```

When i use Spark 2.4.7:
```
library(sparklyr)

sc <- spark_connect('local', version = '2.4.7')

cars <- sdf_copy_to(sc, mtcars)

pipeline <- ml_pipeline(sc) %>% 
  ft_one_hot_encoder(
    input_cols = c('cyl', 'am'),
    output_cols = c('cyl_encoded', 'am_encoded')
  )
```
It returns error like this:
```
Error: OneHotEncoder does not support encoding multiple columns
```

**Comment by yitao-li** [comment]
@CooperChen453 Thanks for the feedback.

I don't see the multiple-column use case being supported in Spark 2.4.7 API: i.e., I don't see `setInputCols` (plural) method here https://spark.apache.org/docs/2.4.7/api/scala/index.html#org.apache.spark.ml.feature.OneHotEncoder

The multiple-column use case appears to be only supported in Spark 3.0 or above: e.g., see `setInputCols` and `setOutputCols` (plural) in https://spark.apache.org/docs/3.0.0/api/scala/org/apache/spark/ml/feature/OneHotEncoder.html

**Comment by yitao-li** [comment]
Looking into the error you mentioned now...
