### ISSUE TITLE
Engineering Improvements

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2273]
We should consider spending some time improving speed of our tests, reliability, clean up code (specially Scala), reducing number of issues in GitHub, etc.

**Comment by yl790** [comment]
@javierluraschi I think I'll be happy to look into improving speed of tests next.

Some obervations:

- Currently looks like Travis only wants to run 5 jobs in parallel at a time. So, splitting the current test workload into even more jobs would not help unless we replace Travis with something else that can run more test jobs concurrently.
- I also tried running multiple test cases in parallel within one test job at some point but I think there were some concurrency issues because of how Spark shell connection is being used. However, I haven't spent a lot of time looking into this direction yet... Maybe there is some way to have more parallelism within each test job.
