### ISSUE TITLE
Best config of Sparklyr + Arrow

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2318]
Hi sparklyr team,
First of all thank you for the great work!
I would like to know which are the best configuration of Spark and Arrow, in terms of parameters, in order to manage a large amount of data, especially when I want to use spark_apply methodology.
I am using an EMR with 2 clusters and connecting to spark with spark_connect (master = "yarn").
There are some rules or guidelines to taking into consideration? Which are the best practices in order to optimize the environment?
Thanks for the support
Best Regards
Stefano

**Comment by yl790** [comment]
@sbottelli I'm by no means an expert on Arrow-related matters. I'll forward this question to an internal chat thread about Arrow at RStudio and see what people will reply.

**Comment by sbottelli** [comment]
Thank you!
I'm waiting for some useful answers!
Regards

**Comment by javierluraschi** [comment]
Hi @sbottelli,

We unfortunately don't have concrete recommendations nor benchmarks at the moment. However, here are some prerequisites and suggestions:

1. Make sure arrow is installed in the driver node and all the worker nodes, this can be accomplished by installing arrow in the EMR bootstrap action. In order to get `arrow` working in EMR, I've had to manually compile Apache Arrow, you can use this script: http://sparklyrec2.s3.amazonaws.com/rstudio_sparklyr_emr5.sh -- However, I believe you also need to increase the EMR creation time since compilation of arrow can take a while. The script is old, so you probably also need that updated.
2. Make sure `library(arrow)` is run to activate Apache Arrow in Spark and R.
3. I recommend using `maximizeResourceAllocation` in EMR, but this is unrelated to Apache Arrow just a practice I follow in general.
4. You shouldn't definitely experience a significant improvement in `spark_apply()`, about 10X, when transferring non-trivial data to the worker nodes using `spark_apply()`, as in, when the table sizes are not trivial.

These instructions are 6 months old, newer versions of the `arrow` package support `arrow::install_arrow()`, so perhaps it simplifies the installation if you install the `arrow` package in each worker node and then run in each worker node `arrow::install_arrow()`.

Let us know what you works and doesn't and we will try to provide a few more pointers.

**Comment by samuel-bohman** [comment]
"You shouldn't definitely experience..."? Do you mean "You should definitely experience..."?

**Comment by sbottelli** [comment]
It's important the comment of @samuel-bohman. Because I'm working with a tons of rows (46 million) and if arrow doesn't help me with performances, I'll not install it on machines

**Comment by yl790** [comment]
Definitely agree that `arrow` is way more efficient than other existing serialization mechanisms in sparklyr. But aside from that I don't think there is any sort of silver bullet that will necessarily increase performance in all scenarios... and a lot of those optimal config values are dependent on how large or small your workload will be, how much memory you have in driver / worker nodes, etc. So, it's better to tweak them based on performance profiling rather than relying on some "rule of thumb" to hold true in all cases.
