### ISSUE TITLE
Build Spark 2.4 jars with Scala 2.12 

### ISSUE THREAD

**Issue by falaki** [sparklyr/sparklyr#2428]
Preparing for Spark 3.0 which drops Scala 2.11 support, we can publish sparklyr backend JARs for Spark 2.4 with both Scala 2.11 and 2.12. We think this will help users with migration.

**Comment by yl790** [comment]
@falaki So is the plan to have user set `spark_config$sparklyr.app.jar` to `"sparklyr-2.4.0-2.12.jar"` when calling `spark_connect` in order to make use of the artifacts built with Scala 2.12?
Asking because currently if user runs `spark_connect(..., version = "2.4")` then the default choice will always be `"sparklyr-2.4.0-2.11.jar"`, even if `"sparklyr-2.4.0-2.12.jar"` also exists.

Also, I will change the existing CI workflow to cover the Spark 2.4 jars built with Scala 2.12 (because otherwise the new `"sparklyr-2.4.0-2.11.jar"` would be completely untested which feels wrong)
