### ISSUE TITLE
Sparklyr + Error in spark_install_find

### ISSUE THREAD

**Issue by mokumar1202** [sparklyr/sparklyr#2447]
---
Hi Guys, I wanted to upgrade Spark from 2.1.1 to 2.3.0 , so i downloaded the spark tar file for version 2.3.0 (source: https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.6.tgz) and unzipped it, pointed the SPARK_HOME to the new version and i am able to launch spark-shell within Linux but when i try to create a connection from Sparklyr, it says Spark version is not installed. Any help will be really appreciated.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.0
      /_/

Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_242)
Type in expressions to have them evaluated.

```r
spark_version <- "2.3.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```
> library(sparklyr)
> library(dplyr)
> spark_version <- "2.3.0"
> sc <- spark_connect(master = "local", version = spark_version)
Error in spark_install_find(version, hadoop_version, latest = FALSE, hint = TRUE) : 
  Spark version not installed. To install, use spark_install(version = "2.3.0")

**Comment by yl790** [comment]
@mokumar1202 At the moment sparklyr assumes all versions of spark are located within `~/spark` by default (i.e., the default is such that spark is installed in user home directory rather than system-wide).

You can change that location with `options(spark.install.dir = "<your directory>")`. As an example, let's say if you set `options(spark.install.dir = "/opt")`, then sparklyr expects required binaries such as `/opt/spark-2.3.0-bin-hadoop2.7/bin/spark-shell`, `/opt/spark-2.3.0-bin-hadoop2.7/bin/spark-submit` to exist as part of your spark installation.

It's way easier to just install spark in the default location though with the following:

```
library(sparklyr)
spark_install("2.3.1")
```

rather than installing it manually. Alternatively, if you really need your spark installation to be available in a system-wide location, then it's still less painful to sym-link the system-wide directory into `~/spark` (e.g., `mkdir -p ~/spark; ln -s /opt/spark-2.3.0-bin-hadoop2.7 ~/spark`) rather than running `options(spark.install.dir = "/opt")` before you do anything with sparklyr.

**Comment by mokumar1202** [comment]
Hi @yl790, 

Thanks for your quick reply. I was under the impression that since the source tar files already had the required binaries that i don't need to install it again, may be i got it all wrong.

Yes your understanding was correct about me putting this in a system-wide location for the users in my wider team to use it. So i have got all my spark binary files (spark-shell, spark-submit, pyspark) in /usr/spark folder. 

What is the configuration that i am missing that i need to set up?

**Comment by yl790** [comment]
@mokumar1202 Assuming you are running a single version of spark on this host and everything is in `/usr/spark` (e.g., `/usr/spark/bin/spark-shell` et al) then I would just do the following:

```
mkdir -p ~/spark
ln -s /usr/spark ~/spark/spark-2.3.0-bin-hadoop2.6
```

but this type of set up is a bit brittle though, because the symlink name tells sparklyr the spark version you have is version 2.3 and intended to work with hadoop2.6, and if you ever upgrade the underlying binary at /usr/spark to higher version, then you need to change the name of this symlink as well (e.g., `spark-2.4.0-bin-hadoop2.7` etc).

If disk space is not a problem, I would recommend having a separate version of spark in `~/spark` that is different from the system-wide spark instead (as this is definitely less confusing compared to the sym-link hack mentioned above...)

**Comment by mokumar1202** [comment]
@yl790 Yes i have a single version of spark on this host and everything is in /usr/spark. I have created the spark directory and the symbolic link but when i tried to install spark it tries to connect to internet and it fails as our server is not configured to access internet content, so i have downloaded the tar file and uploaded it to the server, how do i specify the location of the tar file when i install rather than it automatically trying to download from the repo.

Also another question is if i get this working then should all the people in my wider team need to install spark in their home dir? which seems to be a bit odd as there should be another way of installing it globally and configuring sparklyr to use that spark version but i might be completely wrong here.

**Comment by yl790** [comment]
@mokumar1202 I suggest doing the following:

- On a separate ubuntu host / vm where you can experiment with: install R, install sparklyr, and then run sparklyr::spark_install(version = ... ) in a R shell -- this will install spark in ~/spark and you can examine what is the desired directory structure sparklyr can work with under ~/spark

- Afterward that, go back to the spark driver / worker hosts you and your team need to work with, create sym links that mirror the directory structure from the first step on your "experimental" host / vm

Hopefully this helps. Meanwhile I'll also look into how to make sparklyr support your use case of a global spark installation better.

**Comment by yl790** [comment]
Also re: having /home/$USER/spark for each user -- you can still have a centrally managed spark installation (say `/opt/spark`) and simply sym link /opt/spark to /home/$USER/spark for each user for sparklyr to work with under its default settings of looking for spark installation in ~/spark.

**Comment by mokumar1202** [comment]
@yl790 When i run the command to install it fails as it cannot download the source files, so i have downloaded the tar separately and have loaded it into the server. So how do i install specifying the location of the source file?

> library(sparklyr)
> spark_install("2.3.0")
Installing Spark 2.3.0 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz'
Installing to:
- '/usr/hdp/2.6.2.0-205/spark2/spark-2.3.0-bin-hadoop2.7'
Error in spark_install("2.3.0") : 
  Failed to download Spark: download exited with status 1

**Comment by yl790** [comment]
@mokumar1202 Currently there is no need to run `spark_install` (or any other R command) if you want to install Spark manually. I would just run the following:

```
cd /tmp
wget https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz # you mentioned this was already done
tar xf spark-2.3.0-bin-hadoop2.7.tgz
mv spark-2.3.0-bin-hadoop2.7 /usr/hdp/2.6.2.0-205/spark2  # the default sparklyr location for spark installations is ~/spark, but looks like yours is now /usr/hdp/2.6.2.0-205/spark2 if I understood correctly
# possibly also sym link the spark installation to ~/spark in case it's needed
# mkdir -p ~/spark
# ln -s /usr/hdp/2.6.2.0-205/spark2/spark-2.3.0-bin-hadoop2.7 ~/spark
```

**Comment by mokumar1202** [comment]
@yl790  Brilliant. After following the above steps, issue is sorted out.
