### ISSUE TITLE
No tags for releases v1.1.0 or v1.2.0

### ISSUE THREAD

**Issue by tnixon** [sparklyr/sparklyr#2537]
There are no tags for releases v1.1.0 or v1.2.0

This makes it difficult to debug / verify issues against these versions.

**Comment by yl790** [comment]
@tnixon Hey thanks for asking! I was following the pre-existing convention of having release branches such as  https://github.com/sparklyr/sparklyr/tree/feature/sparklyr-1.2.0 instead of tags when I started working on sparklyr. I guess having branches is better for hot-fixing. Tags are more light-weight though.

Let me know what you think.

**Comment by yl790** [comment]
There is also https://github.com/sparklyr/sparklyr/tree/feature/sparklyr-1.1.0 from sparklyr 1.1 release btw.

**Comment by tnixon** [comment]
Thanks for explaining, that makes sense. Release branches can definitely help in developing hot-fixes.

I think it's confusing to not continue the practice of release tags, since there are tags for older releases. It could be helpful to have both.

**Comment by yl790** [comment]
Updated tags on upstream:

 * [new tag]           v1.1.0 -> v1.1.0
 * [new tag]           v1.2.0 -> v1.2.0

**Comment by tnixon** [comment]
Thanks @yl790 !
