### ISSUE TITLE
lag function for streaming Spark dataframe

### ISSUE THREAD

**Issue by chalioui** [sparklyr/sparklyr#2724]
Hello! I want to know how to implement lag in spark streaming using sparklyr 

---

your brief description of the problem

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)


dir.create("source")


df= data.frame(
  stringsAsFactors = F, 
  id=1, 
  Msg= c("M", "B", "M","M","M","E"), 
  timestamp= as.POSIXct(c("2020/09/10 10:00", "2020/09/10 10:01", "2020/09/10 10:20",
                     "2020/09/10 10:59", "2020/09/10 11:10", "2020/09/10 12:59"))
  
)

stream_generate_test(df = df,iterations = 1)

#stream <- stream_read_csv(sc, "source/") %>%
# stream_write_csv("destination/")
stream_read_csv(sc, "source/") %>% 
  stream_watermark(column = "timestamp") %>% 
  mutate(r=  lag(timestamp))

```
I get errors from spark 

```
Error: org.apache.spark.sql.AnalysisException: Window function lag(timestamp#2986-T600000ms, 1, null) requires window to be ordered, please add ORDER BY clause. For example SELECT lag(timestamp#2986-T600000ms, 1, null)(value_expr) OVER (PARTITION BY window_partition ORDER BY window_ordering) from table;
```
So i added an arrange(timestamp) before mutate  as suggested but I get another error 
```
Error: org.apache.spark.sql.AnalysisException: Sorting is not supported on streaming DataFrames/Datasets, unless it is on aggregated DataFrame/Dataset in Complete output mode;;
```

**Comment by yitao-li** [comment]
@chalioui I don't think the use case you described is supported by Spark streaming yet. I tried the following with Spark 2.3 and in higher versions of Spark up to 3.0.0:

```
library(sparklyr)

spark_version <- "2.3.0"
sc <- spark_connect(master = "local", version = spark_version)

streaming_path <- "source"
dir.create(streaming_path)

df <- data.frame(
  stringsAsFactors = FALSE,
  id = 1,
  Msg = c("M", "B", "M", "M", "M", "E"),
  timestamp = as.POSIXlt(
    c("2020/09/10 10:00",
      "2020/09/10 10:01",
      "2020/09/10 10:20",
      "2020/09/10 10:59",
      "2020/09/10 11:10",
      "2020/09/10 12:59"
    )
  )
)

stream_generate_test(df = df, path = streaming_path, iterations = 1)

lag_offset <- 1L   # read the timestamp from the 1 row prior to the current row

dat <- stream_read_csv(sc, streaming_path) %>%
  stream_watermark(column = "timestamp") %>%
  dplyr::mutate(prev_timestamp = dplyr::sql(LAG(`timestamp`, 1) OVER (ORDER BY `timestamp`)"))

print(dat)
```

All of them threw the following exception:

"org.apache.spark.sql.AnalysisException: Non-time-based windows are not supported on streaming DataFrames/Datasets"

I think what that exception says is you cannot look behind a fixed number of rows in the streaming use case. You can only look behind a fixed time duration.

**Comment by chalioui** [comment]
@yitao-li  Thank you for this response! do you have any suuggestion to impelement an equivalent ? 
I'm trying the cumsum function but I got the same error

**Comment by yitao-li** [comment]
@chalioui I _think_ it should be feasible with the [`mapPartitions`](https://spark.apache.org/docs/2.0.1/api/java/org/apache/spark/streaming/dstream/DStream.html#mapPartitions(scala.Function1,%20boolean,%20scala.reflect.ClassTag)) API of `DStream` in Spark, but for whatever reason, just not supported directly through Spark SQL.

I'll probably explore this bit more and hopefully make it part of `sparklyr` 1.5, and ideally, make this functionality usable through the same `dplyr` lag method as well.

**Comment by yitao-li** [comment]
@chalioui I think I have managed to implement this functionality in sparklyr. You can try it out with the following:

```
install.packages("remotes")
remotes::install_github("yitao-li/sparklyr", ref = "streaming_lag")

# begin: example

library(sparklyr)

sc <- spark_connect(master = "local", version = "2.2.0")

streaming_path <- tempfile("days_df_")
days_df <- tibble::tibble(
  today = weekdays(as.Date(seq(7), origin = "1970-01-01"))
)
num_iters <- 7
stream_generate_test(
  df = days_df,
  path = streaming_path,
  distribution = rep(nrow(days_df), num_iters),
  iterations = num_iters
)

stream_read_csv(sc, streaming_path) %>%
  stream_lag(yesterday = today ~ 1, two_days_ago = today ~ 2) %>%
  collect() %>%
  print(n = 10L)

# end example
```

Let me know what you think.

There is one caveat though: if your data frame has multiple partitions, then there will not be any look behind across the partition boundary. This is by design -- Spark data frame partitions are designed to be processed in parallel in no particular order, so, given the current partition being processed, there is no clear-defined notion of "the previous partition" in Spark, so, any look behind will be only among records within the current partition.

**Comment by chalioui** [comment]
@yitao-li  Works perfectly thank you for this great work!! 
Maybe it make sence to add lag function with with constraint like in azure : https://docs.microsoft.com/en-us/stream-analytics-query/lag-azure-stream-analytics

**Comment by yitao-li** [comment]
@chalioui 

Good suggestion! You can now try the version with additional constraint by running `remotes::install_github("yitao-li/sparklyr", ref = "streaming_lag_with_constraint")`

Example usage:

```
stream_lag(
  cols = c(yesterday = day ~ 1, two_days_ago = day ~ 2),
  thresholds = c(time = "2days")
)
```
for selecting previous values that are within a 2-day time window, assuming `time` is a date column or a timestamp column.

Notice supporting a time window of constant length is probably as far as `sparklyr` can go, because currently the selection and filter logic is implemented entirely in Scala, and anything more complicated such as time window of variable length would require integration with Spark SQL query engine, which would most likely need a non-trivial change in Spark query engine itself to be done efficiently.
