### ISSUE TITLE
Sparklyr “embedded nul in string” when applying spark_apply.

### ISSUE THREAD

**Issue by akashshah59** [sparklyr/sparklyr#2754]
We encounter an embedded nul issue while applying a method to parquet data. 

```
source('spark_function.R')
library(tictoc)
library(arrow)

download.file('https://github.com/akashshah59/embedded_nul_parquet/raw/main/CC-MAIN-20200702045758-20200702075758-00007.parquet','sample.parquet')

temp <- spark_read_parquet(sc,name = 'temp',path = 'sample.parquet')
```
While the spark data frame is created without errors due to sparks lazy evaluation , this particular code snippet breaks when an embedded nul character ‘\0’ is found in a particular string.
```
spark_apply(temp,print)
```

This spark_apply generates the following stacktrace -  

```
20/10/14 18:13:27 INFO sparklyr: Worker (8674) launching command Rscript --vanilla /media/nessmain/spark_temp/spark-16b30cca-8778-4b6c-a512-387e597ee5d5/userFiles-89f97e36-6826-491d-91a1-23aa2c8bb9fd/sparkworker_8674.R 8674 43041 FALSE;8880;localhost;FALSE;FALSE;TRUE;TRUE;2.4.3
20/10/14 18:13:27 INFO sparklyr: Worker (8674) is starting R process
.
.
.
.

20/10/14 18:13:33 INFO sparklyr: RScript (8674) is processing batch 3 
20/10/14 18:13:33 ERROR sparklyr: RScript (8674) terminated unexpectedly: embedded nul in string: '\0 at \0' 
(20/10/14 18:13:33 INFO sparklyr: Session (8674) is shutting down with expected SocketException,java.net.SocketException: Socket closed)
20/10/14 18:13:33 ERROR Executor: Exception in task 0.0 in stage 39.0 (TID 20069)
java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:83)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:125)
```

Is there a sparklyr method or function argument that can help skip these nul’s from parquets efficiently? Is there a way we can read and return the binary for every row?
I tried using `arrow::write_to_raw()` however it returns the entire parquet file as raw and the nuls are indecipherable.

**Session Info**

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0  dplyr_1.0.2    tictoc_1.0     arrow_1.0.1    sparklyr_1.4.0
```

**Comment by yitao-li** [comment]
@akashshah59 Your code runs fine without `arrow`, so, I think it's a bug with `arrow`, and more specifically, it's when `arrow` tries to collect results from Spark back to R.

Other observations:
- If I run something like ` spark_apply(temp %>% dplyr::sample_frac(0.02), function(x) 42L)` with `arrow` enabled (which reads a small random subset of the input, does nothing, and then return a number, the process would still fail randomly if it hits some records from `temp` (but it appears to work with the vast majority of the other records).
- I also noticed the input has UTF8 characters in them, so maybe `arrow` is not working well with some particular UTF8 input, which is annoying : /
- A number of other operation works as expected -- e.g., `dplyr::select`, `dplyr::filter`, as long as your query result stays inside a Spark dataframe, but if you try to collect those query results back to R using `arrow`, the embedded nul error might happen. 
- `temp %>% collect()` does not work with `arrow` either.

Anyhow I think at the moment you can either avoid `arrow` (but suffer from slower serialization) or continue using `arrow` but try to find and avoid inputs that `arrow` is not happy with. None of those seems like a good option, but I haven't found other workarounds (yet).

I would also suggest avoid `spark_apply` unless you really must run R code on your data and don't have other alternatives -- if you run `spark_apply`, the data is first read from parquet files into a Spark dataframe, and then parts of the Spark dataframe gets fetched from Spark to R as a R dataframe so that a Spark worker process can run your R code on that R dataframe, and then results get serialized back to Spark again, all of which incurring non-trivial serialization overhead.

**Comment by yitao-li** [comment]
Update: actually your input does contain embedded nul -- if I don't use `arrow` for serialization at all, there is still a warning message saying "In readString(con) : Input contains embedded nuls, removing" which is thanks to a PR that @jozefhajnala created to avoid failing on embedded nuls. It only works on non-arrow use case though.

**Comment by yitao-li** [comment]
@akashshah59 

Actually as a workaround, you simply need the following:

```
library(sparklyr)
library(arrow)

sc <- spark_connect(...)
temp <- ...

temp %>%
  dplyr::mutate(raw = dplyr::sql("CAST(`raw` AS BYTE)")) %>%
  spark_apply(print)
# ^^ but whatever R function you end up applying now needs to take into consideration the `raw` column of the R dataframe it receives contains a raw vector instead of a character vector in R 
```
