### ISSUE TITLE
Records per partition

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2791]
Hi!
I have a question: how can I see the number of records per partition?
I want to know how the records are distributed in order to see some skewness in the data and eventually adjust them with some workarounds (to speed up performances)
Thanks for the hard work that you do for mantain this very outstanding package!
Regards
Stefano

**Comment by yitao-li** [comment]
@sbottelli Good question!

At the moment you can run `spark_apply(sdf, function(x) nrow(x))` to get the partition sizes (probably not very efficient, but does get the job done).

**Comment by yitao-li** [comment]
Also notice if you just want to know whether some partition strategy will produce skew or not, it probably makes sense to apply that partition strategy to some subset of data and then run `spark_apply(...)` from my previous comment on that subset. `spark_apply` could be slow when running on large number of rows.

**Comment by sbottelli** [comment]
Thanks @yitao-li ! I will test it!

**Comment by yitao-li** [comment]
@sbottelli I think it may also be a good idea to first only select the subset of column(s) you are partitioning with into a smaller dataframe -- otherwise it looks like Spark might start computing all other columns which are irrelevant to distribution of rows in partitions (I could be wrong on this one though but it doesn't hurt to guard against computations that are unnecessary)

**Comment by sbottelli** [comment]
yes, I partition the table by using an ID column and then calculating the distribution of rows in each partition to examine skew.

Thanks for thecode, the tricks and the clear answer!

**Comment by benmwhite** [comment]
`spark_apply(sdf, function(x) nrow(x))`

@yitao-li this is one of the hackiest uses of `spark_apply()` I've ever seen, I love it
