### ISSUE TITLE
performance regression in readDate method

### ISSUE THREAD

**Issue by MrBago** [sparklyr/sparklyr#2821]
Collecting dataframes with date columns is about 300x slower in sparklyr 1.3 & 1.4 compared to version 1.2.

To reproduce the issue I created a temp view in spark with ~5 million rows with either a DateType or StringType. When a date type is included the collect time is much slower (~100x). This issue didn't exist in version 1.2. I profiled the code and it seems most of the execution time is spent in `readDate`, though I can't tell if it's actually something in readDate of the it's blocking on input from Spark.

Create temp views in spark:

```
val N = 5000000
val a = sc.parallelize((0 until N).map(i => MyDateRow(new Date(i * 24 * 60 * 60 * 1000)))).toDF
a.createOrReplaceTempView("tableWithDateColumn")
val b = sc.parallelize((0 until N).map(i => MyStringRow(new Date(i * 24 * 60 * 60 * 1000).toString))).toDF
b.createOrReplaceTempView("tableWithStringColumn")
```

Query temp views:
```
# fast query
m <- sdf_sql(sc, "select * FROM tableWithStringColumn") %>% collect()

# slow query
m <- sdf_sql(sc, "select * FROM tableWithDateColumn") %>% collect()

```

**Comment by yitao-li** [comment]
@MrBago In sparklyr 1.3 and above date values had to be collected as yyyy-mm-dd strings instead of as UNIX timestamps from Spark back to R because the latter was problematic when the JVM time zone is not matching time zone of the user's R session (e.g., 1970/01/01 gets collected as 1969/12/31 because of different time zone offsets)

Please consider using `arrow` to speed up (de)serialization if you find (de)-serialization speed becoming a bottleneck (see https://spark.rstudio.com/guides/arrow).

We are also currently exploring the possibility of using RDS format for transporting data from Spark back to R which might improve the performance of sdf_collect for non-arrow use cases.

**Comment by MrBago** [comment]
@yitao-li we did try arrow, and from what I remember, it didn't help, but we I'll take another look. I think there should be some low hanging fruit in terms of reducing the Date serde time because the String version of "yyyy-mm-dd" takes ~100 less time than the Date object. I think there's something unnecessary happening either when the Date is being converted to a string or when it's being converted back to a Date.
