### ISSUE TITLE
Charset/Encoding Latin Character

### ISSUE THREAD

**Issue by celina-oliv** [sparklyr/sparklyr#2870]
I am having problems reading txt files with column headings with Latin characters, such as: "ç".

My command used is:

spark_read_csv (sc = sc, path = "txtfile", charset = "latin1", name = "mydata", delimiter = ";", header = T)

When I look at mydata, the columns come out as follows:

- "Município" => "MunicApio"
- "Vínculo_Ativo" => "VAnculo_Ativo"

**Comment by yitao-li** [comment]
@celina-oliv At the moment `sparklyr` "translates" non-ASCII characters into ASCII ones using `iconv`. This was presumably because Spark or other database backends such as Hive didn't have good support for non-ASCII column names yet back in 2016. I'm not sure whether this is currently still the case or not.

Do you think there should be a configuration that disables the `iconv` conversion so that non-ASCII column names are preserved when importing data into Spark? (keeping in mind that once data is imported into Spark, everything querying the imported Spark dataframe will need to be able to work with non-ASCII column names)

**Comment by celina-oliv** [comment]
In 2016 I used SparkR directly on R, I didn't use Sparklyr. In that time, I opened the columns with their real names. The command used was read.df with the following arguments:

y2<-read.df(sqlContext, path.file, source = "com.databricks.spark.csv",header="true",
                    delimiter = ";", inferSchema='true', codec="org.apache.hadoop.io.compress.GzipCodec", 
                    charset='latin1')

It worked. Today I would like to use Sparklyr, but I encountered this problem. I will try to configure the incov.
