### ISSUE TITLE
Runtime spark connection config

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2872]
Hi team!
How can I modify spark_connection parameters in a runtime fashion?
For example:

`conf <- spark_config()`
`sc <- spark_connect(master = "local", config = conf)`

How can modify "sc" object after the connection?

Best Regards,
Stefano

**Comment by benmwhite** [comment]
I don't think this is possible without disconnecting and starting a new Spark session with your updated config.

**Comment by sbottelli** [comment]
Thanks for the reply!

**Comment by yitao-li** [comment]
Yep. The Spark connection objects should never be modified directly in `sparklyr` (aside from `spark_disconnect(sc)`) as any change would not be reflected on the ongoing Spark session.

Feel free to file a more specific feature request if you need to update the Spark session in some way and you believe there should be an idiomatic way to accomplish it in R.

Also, modifying a Spark session could be tricky because (what I remember from the last time I checked) only some subset of `spark.sql.*` properties can be meaningfully updated while the session is running.
