### ISSUE TITLE
Update docs to recommend sparklyr::sdf_sql() over DBI::dbGetQuery()

### ISSUE THREAD

**Issue by ColeMiller1** [sparklyr/sparklyr#2922]
The main [README](https://github.com/sparklyr/sparklyr/blob/main/README.Rmd) mentions using `DBI::dbGetQuery()` to execute SQL. this seems very slow in comparison to use `sparklyr::sqf_sql()`. Could the docs be updated?

```r
library(sparklyr)
library(DBI)
sc <- spark_connect(master = "local")
invisible(copy_to(sc, iris))
bench::mark(sparklyr_sql = sdf_sql(sc, "SELECT * FROM iris LIMIT 10"),
            DBI_sql = dbGetQuery(sc, "SELECT * FROM iris LIMIT 10")
            , check = FALSE)

## # A tibble: 2 x 13
##   expression        min   median `itr/sec` mem_alloc     
##   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>
## 1 sparklyr_sql    100ms    113ms      8.86  317.77KB
## 2 DBI_sql         610ms    610ms      1.64    1.43MB

spark_disconnect_all()
```

**Comment by yitao-li** [comment]
@ColeMiller1 Good question! The two functions are in fact very different: `DBI::dbGetQuery()` also fetches the execution result back to R (therefore causing your input SQL to be evaluated immediately), whereas `sdf_sql()` doesn't. In fact, if you simply run `sdf_sql()` without "demanding" the execution result to be sent from Spark back to R [*], then your SQL won't be evaluated at all because Spark dataframes are evaluated lazily. 

[*]: In `sparklyr` there are a couple of ways to get a Spark dataframe back to a R dataframe: calling `print()` explicitly or implicitly in an interactive R prompt on the Spark dataframe, or calling `collect()` explicitly on the Spark dataframe
