### ISSUE TITLE
Random failures in spark_connect() for concurrent connections (>10)

### ISSUE THREAD

**Issue by shujaat-ali** [sparklyr/sparklyr#2934]
When concurrent spark jobs are submitted then randomly for few jobs we get below pasted error.
 
==============================
21/02/10 16:22:02 INFO sparklyr: Session (51512) is starting under 127.0.0.1 port 10407
21/02/10 16:22:02 INFO sparklyr: Session (51512) found port 10407 is available
21/02/10 16:22:02 INFO sparklyr: Gateway (51512) is waiting for sparklyr client to connect to port 10407
21/02/10 16:23:02 INFO sparklyr: Gateway (51512) is terminating backend since no client has connected after 60 seconds to 192.168.162.54/10407.
21/02/10 16:23:02 INFO ShutdownHookManager: Shutdown hook called
21/02/10 16:23:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-6611f5d2-4fa6-4db3-b1d1-f7da93bbf332
Error in force(code) :
  Failed while connecting to sparklyr to port (10407) for sessionid (51512): Sparklyr gateway did not respond while retrieving ports information after 120 seconds
    Path: /usr/hdp/3.1.5.0-152/spark2/bin/spark-submit
    Parameters: --keytab, /xxxxxxxxxx.keytab, --principal, XXXXXXXXX, --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.3-2.11.jar', 10407, 51512
    Log: /tmp/RtmpW27sow/file1f40c14cfcee7_spark.log

---- Output Log ----

---- Error Log ----
Calls: get_spark_context ... tryCatchOne -> <Anonymous> -> abort_shell -> <Anonymous> -> force
Execution halted
================================

**Comment by yitao-li** [comment]
@shujaat-ali I see your log mentions HDP, so, I assume you are working with a Spark cluster managed by YARN, right? `sparklyr` will submit a Spark application (which is named `sparklyr` by default unless you specified a different name in `spark_connect()`). This application, just like other Spark applications, will go into some job queue in the cluster. You can check what happened to the application through your Spark cluster's web UI.

**Comment by allava** [comment]
We are having the same issue. We have an app deployed to Connect. When multiple Spark jobs are submitted about the same time we find most of them fail to create a connection. We submitted the Connect diagnostics to Rstudio team, who recommended we contact sparklyr team on this issue. The diagnostic log looks like this:

2021/02/14 00:39:07 Reaping /raid1/rstudio-connect/jobs/461/TZLjNdkmvdoHircL
2021/02/14 00:43:53 [app: 449; bundle: 2777] Preemptively starting a new worker due to load factor; currently have 0 conns across 1 workers
2021/02/14 00:43:53 [app: 449; bundle: 2777] WorkerStart {workerId:b36775d2}
2021/02/14 00:43:53 [id 449; worker b36775d2; process 42115] Connecting to worker on port 35668 ...
2021/02/14 00:43:58 [id 449; worker b36775d2; process 42115] Connected to worker on port 35668
2021/02/14 00:44:07 Reaping /raid1/rstudio-connect/jobs/596/P1XaBrup05gex8Dx
2021/02/14 00:44:23 [app: 449; bundle: 2777] Worker b36775d2 is not needed because there are 1 connections across 2 workers giving a load factor of: 0.5
2021/02/14 00:44:23 [app: 449; bundle: 2777] Stopping process for worker b36775d2
2021/02/14 00:44:23 [app: 449; bundle: 2777] WorkerRetire {workerId:b36775d2}
2021/02/14 00:44:23 [id 449; worker b36775d2; process 42115] Worker complete: exited normally with code 137, signal 9 (SIGKILL)
2021/02/14 00:59:07 Reaping /raid1/rstudio-connect/jobs/461/KPnUYBWho9lR3PiJ
2021/02/14 00:59:07 Reaping /raid1/rstudio-connect/jobs/461/R1fLAsfYWnBaJte7
2021/02/14 00:59:07 Reaping /raid1/rstudio-connect/jobs/449/FsIZ2UoN1T8SyqNY
2021/02/14 01:09:07 Reaping /raid1/rstudio-connect/jobs/449/oUsm5nlei6ypAnAc
2021/02/14 01:09:07 Reaping /raid1/rstudio-connect/jobs/449/MSynjnFRcVB8yBh6
2021/02/14 01:22:21 [worker: c394e747; session: 58zocwko] sockjs proxy: Client connection closed
2021/02/14 01:22:21 [worker: c394e747; session: 58zocwko] sockjs proxy: Shiny connection closed
2021/02/14 01:26:23 [app: 449; bundle: 2777] Preemptively starting a new worker due to load factor; currently have 0 conns across 1 workers
2021/02/14 01:26:23 [app: 449; bundle: 2777] WorkerStart {workerId:a9d2c8d7}
2021/02/14 01:26:23 [id 449; worker a9d2c8d7; process 1621] Connecting to worker on port 34439 ...
2021/02/14 01:26:29 [id 449; worker a9d2c8d7; process 1621] Connected to worker on port 34439
2021/02/14 01:26:53 [app: 449; bundle: 2777] Worker a9d2c8d7 is not needed because there are 1 connections across 2 workers giving a load factor of: 0.5
2021/02/14 01:26:53 [app: 449; bundle: 2777] Stopping process for worker a9d2c8d7
2021/02/14 01:26:53 [app: 449; bundle: 2777] WorkerRetire {workerId:a9d2c8d7}
2021/02/14 01:26:54 [id 449; worker a9d2c8d7; process 1621] Worker complete: exited normally with code 137, signal 9 (SIGKILL)
2021/02/14 01:34:07 Reaping /raid1/rstudio-connect/jobs/449/bRTjgZqKzp1T6whP

**Comment by allava** [comment]
> @shujaat-ali I see your log mentions HDP, so, I assume you are working with a Spark cluster managed by YARN, right? `sparklyr` will submit a Spark application (which is named `sparklyr` by default unless you specified a different `app_name` in `spark_connect()`). This application, just like other Spark applications, will go into some job queue in the cluster. You can check what happened to the application through your Spark cluster's web UI.

Here is one of our logs found on the attempted spark job. Not sure what 'Gateway (83812) Failed to get network interface of gateway server socketnull' suggests?

21/02/12 09:04:03 INFO security.AMCredentialRenewer: Scheduling login from keytab in 18.0 h.
21/02/12 09:04:03 INFO yarn.ApplicationMaster: Preparing Local resources
21/02/12 09:04:03 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1611881537061_140937_000002
21/02/12 09:04:03 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
21/02/12 09:04:03 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
21/02/12 09:04:03 WARN sparklyr: Gateway (83812) Failed to get network interface of gateway server socketnull
21/02/12 09:05:03 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Shutdown hook called before final status was reported.)
21/02/12 09:05:03 INFO yarn.ApplicationMaster: Deleting staging directory

**Comment by yitao-li** [comment]
@allava Your diagnostic log suggests the OS (presumably Linux) found itself running out of memory and had to terminate Spark worker processes to free up memory (as evident from exit code 137 => signal 9). I general when the OS is out of memory, it chooses processes to terminate based on some heuristics. See https://www.kernel.org/doc/gorman/html/understand/understand016.html
