### ISSUE TITLE
Error when using a UDF after collect_list

### ISSUE THREAD

**Issue by chisqr** [sparklyr/sparklyr#3054]
Hello,

I am trying to apply a UDF after using the collect_list function. Here is a reproducible code:

```r
tab <- data.frame(a = c(1, 1, 1, 2, 2), b = c(1, 2, 3, 1, 2))
tab <- copy_to(scon, tab, overwrite = TRUE)

tab <- tab %>%
  group_by(a) %>%
    summarise(val = collect_list('b')) %>%
  ungroup()

udf <- function(df) {
  print('hello spark!')
  return(data.frame(val = 1.1))
}

res <- tab %>%
 spark_apply(udf, columns = list(val = "double")) %>%
 collect()
```
Here is the callstack from one of the executor nodes:

```r
10: stop("invalid list argument: all variables should have the same length")
9: (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = default.stringsAsFactors()) 
{
    match.names <- function(clabs, nmi) {
        if (identical(clabs, nmi)) 
            NULL
8: do.call(rbind.data.frame, c(data, list(stringsAsFactors = FALSE)))
7: spark_worker_apply(sc, config)
6: doTryCatch(return(expr), name, parentenv, handler)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
```
I am using R v3.6.0, sparklyr v1.6.2 and Spark  v2.4.0

I would really appreciate some tips to make this work. 

Also is there some way to view/modify the R script generated by sparklyr that is executed on the executor nodes ? From line 8 of the callstack I can see that sparklyr is trying to concatenate a list of rows. How do I directly iterate over this list, instead of doing an expensive rbind operation for large tables ?

Thanks!

**Comment by yitao-li** [comment]
@chisqr Interesting question! I believe the error is because spark_apply relied on `rbind.data.frame` which does not handle list columns well. I was also looking over https://github.com/tidyverse/tibble/issues/34 (which I think is somewhat related to this) but did not see a solution there.

**Comment by chisqr** [comment]
Well, in that case if I can some how comment out line 8 where rbind occurs then I could handle the transformation of the list of dataframes and do rbind with a more reasonable dataframe structure within the UDF.

**Comment by yitao-li** [comment]
@chisqr I think the best fix I can think of is the following:

Instead of running
```
do.call(rbind.data.frame, c(data, list(stringsAsFactors = FALSE)))
```

which won't work for inputs with list column(s) on the Spark worker node, run

```
data <- do.call(
  dplyr::bind_rows,
  lapply(
    data,
    function(x) {
      tibble::as_tibble(x, .name_repair = "universal")
    }
  )
)
```
instead.

However, the latter will only work if `dplyr` and `tibble` are installed on all Spark worker nodes.

Now typically `spark_apply` will only assume only base R functions are available on worker nodes and cannot assume other R packages are installed as well. So the only option left is run the latter version only if both `dplyr` and `tibble` are installed on the current worker node, but that could potentially cause some potential debugging headache as well -- i.e., what if some worker nodes had `dplyr` and `tibble` installed and some did not? I think the answer is your `spark_apply` workload might suceed _by luck_ if all worker nodes running the closure happen to have `dplyr` and `tibble` installed and then fail at some other time if that's not the case... : / So, this is like a playing Russian roulete and hoping for the best sort of scenario. Hopefully I'm making sense.

Anyhow, as of now there is only the imperfect workaround above. No perfect solution yet unfortunately.

**Comment by yitao-li** [comment]
@chisqr No you cannot just comment out `rbind` -- somewhere in the current `spark_apply` implementation there is the problem of converting list of columns into data frames, where either `rbind` from base R is needed (which does not handle nested list columns) or alternatively `dplyr::bind_row` as shown above (which handles list columns and also is more efficient than `rbind` from base R btw).

**Comment by chisqr** [comment]
Thank you @yitao-li  for your messages. Where do I add your code snippet in my code above ? The R script for the worker nodes seems to be autogenerated when collect is called. Also, if I include the packages dplyr and tibble in my current environment then won't they be copied over to the worker nodes before RScript is invoked  ?

**Comment by yitao-li** [comment]
@chisqr The workaround will require a change to `sparklyr` itself, and I plan to create a PR for it soon.
No there is no easy way to modify the worker R script auto-generated by `spark_apply`.

If have `dplyr` and `tibble` in your current R env, then by default `spark_apply()` will copy them to all worker nodes. In that case the above will work.

**Comment by chisqr** [comment]
Yes, indeed, I am used to working in Scala for Spark.

**Comment by yitao-li** [comment]
https://github.com/sparklyr/sparklyr/pull/3055 should fix the issue.
