### ISSUE TITLE
release sparklyr 1.6.3

### ISSUE THREAD

**Issue by lresende** [sparklyr/sparklyr#3089]
After upgrading to SparklyR 1.6.2 we are experiencing slow performance and are affecting some production systems. I have noticed that some of the existing issues are already available in the 1.7.0 feature branch, but as this is affecting 1.6.2 users, I would like to propose we do a 1.6.3 with the following fixes: #3024 #3023 #3014 #3013

We have tested these changes and validated that performance is back to comparable values to before 1.6.2

To help with that, I have created a 1.6.3 feature branch to speed up the release process
https://github.com/lresende/sparklyr/tree/feature/sparklyr-1.6.3

**Comment by yitao-li** [comment]
@lresende Shall I go ahead and release sparklyr 1.7.0 instead (as I was actually about to kick off that process)?

Sparklyr 1.7.0 will contain the perf fix plus some other improvements, and will not contain any change that makes `dplyr` performance worse.

**Comment by yitao-li** [comment]
CRAN may have constraints on how often a package maintainer can release a package so we might run into some problem if releasing 1.7.0 immediately after 1.6.3

**Comment by lresende** [comment]
I would prefer 1.6.3 to avoid possible issues from other additional changes to 1.7.0 as we already performed all the tests based on 1.6.3.

**Comment by yitao-li** [comment]
Cool. I'll try to do a 1.6.3 release shortly.

**Comment by lresende** [comment]
Thank you.

**Comment by stepl** [comment]
@yitao-li do you have an ETA by when the 1.6.3 will be available? I'm working with @lresende and we do have some urgency to get a 1.6.3 release with these performance fixes included.

**Comment by yitao-li** [comment]
@lresende @stepl ETA would be by end of this week.

Reason the CRAN release does not happen instantaneously: after a package passes automatic validation at CRAN, it usually still needs to be inspected by an admin at CRAN manually. The queue for manual inspection could take 1-2 days and if manual inspection comes back with documentation issues that need to be addressed (because CRAN is fairly strict about everything) then the entire release process needs to be repeated again.

I don't think there is need for you to wait for a CRAN release though. I will double-check everything is working in the 1.6.3 release branch today, and then you can simply run `remotes::install_github(...)` to install the hotfixed version of `sparklyr` directly from github.

**Comment by yitao-li** [comment]
Update: all validations passed & package submitted to CRAN just now

**Comment by wanting0wang** [comment]
![image](https://user-images.githubusercontent.com/25274600/120338463-41e67b80-c2c2-11eb-9e58-61e5331c55a6.png)

Trying to install it on a windows test machine but it seems like only the source file is updated to 1.6.3...?

**Comment by yitao-li** [comment]
@wanting0wang For windows you will need to wait for CRAN to build the corresponding binary packages.

**Comment by wanting0wang** [comment]
I see, didn't realize CRAN builds the binary packages!

**Comment by yitao-li** [comment]
@lresende @stepl Good news: the source package of `sparklyr` 1.6.3 is on CRAN now.

(there was no need for manual inspection of `sparklyr` 1.6.3 from CRAN this time around, so the release process completed much faster than I originally anticipated)
