### ISSUE TITLE
SparklyR 1.7.0 is missing sparklyr-3.0-2.12.jar

### ISSUE THREAD

**Issue by lresende** [sparklyr/sparklyr#3124]
SparklyR 1.7.0 is missing sparklyr-3.0-2.12.jar
https://github.com/sparklyr/sparklyr/tree/feature/sparklyr-1.7.0/inst/java

**Comment by lresende** [comment]
I see that this might be related to both jars being [identical](https://github.com/sparklyr/sparklyr/blob/50ddb7f8c6c0b923defa386288eb0de320f22563/R/spark_extensions.R#L190) (sparklyr-3.0-2.12.jar and sparklyr-master-2.12.jar). While I understand the intentions here, these jars are very small (400k) and having a consistent list of files allows for better automation of deployments, and avoids confusion.

**Comment by yitao-li** [comment]
@lresende This was done on purpose. CRAN requires any submission to be 5Mb or less in build size, and because `sparklyr` needs to ship a number of jar files for a range of Spark versions, for this release one of {sparklyr-3.0-2.12.jar, sparklyr-master-2.12.jar} had to be omitted. There was also the issue with Databricks runtime falling back to sparklyr-master-2.12.jar when it does not find a jar file that matches the Spark version exactly. We had to keep sparklyr-master-2.12.jar so that Databricks runtime can work with spakrlyr + Spark 3.0.1 or beyond.

It is perfectly valid to copy or symlink java/sparklyr-master-2.12.jar to java/sparklyr-3.0-2.12.jar in the directory of sparklyr installation btw.

**Comment by yitao-li** [comment]
Suggestions are welcome. But for now, given the constraints listed above, especially the CRAN-related ones, I think the easiest option is to perform the following steps (which are fairly trivial to implement BTW) in your deployment automation:

- check for java/sparklyr-3.0-2.12.jar in the directory where sparklyr has been installed
- if it's not present, then symlink java/sparklyr-master-2.12.jar to java/sparklyr-3.0-2.12.jar

**Comment by yitao-li** [comment]
Hey @lresende I just found out the aforementioned workaround for some peculiarity of Databricks runtime would cause sparklyr to not work with **Spark 3.1.x**

Please note sparklyr + Spark 3.1.x is not officially supported by sparklyr yet, but that should change soon, given that Spark 3.1.x has been around for a while.

Meanwhile, in case you need sparklyr to work with Spark 3.1.x now, please either run `remote::install_github("yitao-li/sparklyr", ref = "bugfix/spark-3.1.x-compat")` to essentially pick up a small change on top of the recently released sparklyr 1.7.0, or alternatively, wait for the release of sparklyr 1.7.1 which will contain this change.
