### ISSUE TITLE
Add sparklyr-3.0-2.12.jar to sparklyr/inst/java

### ISSUE THREAD

**Issue by mzorko** [sparklyr/sparklyr#3130]
Hi, Can you add sparklyr-3.0-2.12.jar file back to the sparklyr/inst/java folder?

Our EMR Livy connection stopped working and we think it is because this .jar file is missing.

It was there before: https://github.com/sparklyr/sparklyr/tree/b012cd8afa66a2ecc505d2fda4fb06b0ba9ebe36/inst/java

Thanks,
Mislav

**Comment by mzorko** [comment]
No need, upgraded to the lastest sparklyr version solved the issue

**Comment by yitao-li** [comment]
Yep. There was a minor issue with Spark 3.1.x in the recently published `sparklyr` 1.7.0 unfortunately, and another version of `sparklyr` without this issue should be on its way to CRAN soon as `sparklyr` 1.7.1.

The sparklyr-master-2.12.jar file has always been exactly identical to sparklyr-3.0-2.12.jar.

I had to remove sparklyr-3.0-2.12.jar and keep sparklyr-master-2.12.jar because:
- Size constraint from CRAN submission implies I need to remove one of them
- Databricks runtime needs sparklyr-master-2.12.jar to work, so, sparklyr-3.0-2.12.jar has to go

**Comment by mzorko** [comment]
Hi Yitao,

We upgraded to the newest version and connection is working again.

Thanks for your support.

BR,
Mislav
