### ISSUE TITLE
LM fails on sparklyr with categorical predictors

### ISSUE THREAD

**Issue by DSLituiev** [sparklyr/sparklyr#3139]
I'm trying to run `lm` on `sparklyr` with categorical predictors. 
An example that works in plain R fails in sparklyr:

```R
# this works
lm(Petal.Length ~ as.factor(Species), data = iris)

# this fails
library(tidyverse)
library(sparklyr)

sc <- spark_connect(master = "local")
iris_tbl <- sdf_copy_to(sc, iris)

spark_apply(
    iris_tbl,
    function(e) broom::tidy(lm(Petal_Length ~ as.factor(Species), e)),
    names = c("term", "estimate", "std.error", "statistic", "p.value"),
    # group_by = "Species"
    )
```

I was trying to imitate [this example](https://spark.rstudio.com/guides/distributed-r/#distributing-packages) and simply replaced independent variable to be categorical.

Error log:
```
...
21/06/09 22:48:01 ERROR sparklyr: RScript (3130) terminated unexpectedly: contrasts can be applied only to factors with 2 or more levels 
21/06/09 22:48:01 ERROR sparklyr: RScript (3130) collected callstack: 
16: stop("contrasts can be applied only to factors with 2 or more levels")
15: `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])
14: model.matrix.default(mt, mf, contrasts)
13: model.matrix(mt, mf, contrasts)
12: lm(Petal_Length ~ as.factor(Species), e)
11: broom::tidy(lm(Petal_Length ~ as.factor(Species), e)) 
(21/06/09 22:48:01 INFO sparklyr: Session (3130) is shutting down with expected SocketException,java.net.SocketException: Socket closed)
21/06/09 22:48:01 ERROR sparklyr: Worker (3130) failed to complete R process
(21/06/09 22:48:01 ERROR sparklyr: Worker (3130) failed to run rscript: ,java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.)
21/06/09 22:48:01 INFO sparklyr: Worker (3130) completed wait using lock for RScript
21/06/09 22:48:01 ERROR Executor: Exception in task 0.0 in stage 704.0 (TID 5010)
java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:83)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:125)
21/06/09 22:48:01 INFO sparklyr: Session (3130) is terminating backend
21/06/09 22:48:01 ERROR TaskSetManager: Task 0 in stage 704.0 failed 1 times; aborting job
...
```

I tried posting [this on Stackoverflow](https://stackoverflow.com/questions/67912638/sparklyr-lm-with-categorical-predictors) but got no response

**Comment by jfarland** [comment]
This is a fairly common error message that lets you know that the categorical variable you tried to run a regression on either (a) isn't properly cast as a factor, or (b) as it's message implies, there's less than the required 2 levels of the factor. Since this stems from R's `lm` function, you can validate and fix this in base R first, before adding `sparklyr` back into the mix. I'd just make sure that  `Species` is being cast as a factor, rather than a character. Hope that helps.

**Comment by jfarland** [comment]
I actually tried replicating this error myself and saw the same issue as you.  After debugging a bit, I found out that I was right regarding the fact Species was being treated as a character column inside the `sparklyr` closure. This is due to the fact that `spark_apply` will sample 10 rows in order to determine a schema for a data frame. There are two ways to address this that I found in the documentation; you can either set a value for the columns argument (e.g., `columns = c(Species = 'factor')`) or set a different default number of rows for schema to be identified. I went with the latter and this works for me:

```
library(tidyverse)
library(sparklyr)

config <- spark_config()
config$`sparklyr.apply.schema.infer` <- 150

sc <- spark_connect(master = "local", config = config)

iris_tbl <- sdf_copy_to(sc, iris)

spark_apply(
  iris_tbl,
  function(e) broom::tidy(lm(Petal_Length ~ as.factor(Species), e)),
  names = c("term", "estimate", "std.error", "statistic", "p.value")
)

```

**Comment by DSLituiev** [comment]
> you can either set a value for the columns argument (e.g., columns = c(Species = 'factor')) 

so does that imply that sparklyr does not inherit the column types automatically? the `Species` column is a factor originally

```r
> iris %>% tibble()
# A tibble: 150 x 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
```
 if so, is it by design or omission? Wouldn't this be a nice feature?

**Comment by yitao-li** [comment]
@DSLituiev I don't think a Spark dataframe has the exact equivalent of categorical values in R, so the workaround above is the best one can do at the moment.
