### ISSUE TITLE
Distributing the R library across the hadoop worker nodes - Spark / Hadoop

### ISSUE THREAD

**Issue by Harrymsys** [sparklyr/sparklyr#3152]
Hi Team,

I have the following setup, 

**Machine 1 (not hadoop cluster)** : Spark Client / Driver code with all R libraries in it. Request for spark jobs will be triggered from this node   
**Machine 2, 3 ,4 (All 3 nodes are hadoop worker nodes) :** Spark jobs will be running in these worker nodes. 

**Issue** : I cannot install the R lib / Rscript to these machines (Hadoop worker nodes) - 2, 3, 4 

Is there a way to distribute / copy the R libraries and R / Rscript binaries to these worker nodes (2,3,4) from the spark job initiated from Machine 1.

I come across this solution using sparklyr (https://stackoverflow.com/questions/49717181/how-to-use-spark-apply-bundle) and I tried in the machine one like below and unsuccessful. 

    library(sparklyr)
    
    tar_file <- "/xxx/xxx/r.tar"
    hdfs_path <- "hdfs:///home/r_loc/"
    # 1. Copy the r.tar to the hadoop 
    system(paste("hdfs dfs -put", tar_file , hdfs_path))
    
    # set the config 
    config <- spark_config()
    config$sparklyr.shell.files <- hdfs_bundle 
    # Pass the config as argument
    sc <- spark_connect(master = "yarn-client", config = config)
    

I am stuck here, Not sure how to apply the **spark_apply** 

Queries : 
1) Is there a way to distribute / copy the R libraries and R / Rscript binaries to these worker nodes (2,3,4) from the spark job initiated from Machine 1. 
Any code samples are appreciated. 

Thanks,  
Mathew

**Comment by yitao-li** [comment]
@Harrymsys Please see the top-voted answer from https://unix.stackexchange.com/questions/149451/install-r-in-my-own-directory  -- You need to install R as non-root user on those machines. Simply copying R libraries and R binaries may or may not work because copies of R libraries and R binaries built on one machine link to the version of glibc on that machine, and that won't work if other machines do not contain the same version of glibc at the same location.

**Comment by yitao-li** [comment]
Also `spark_apply()` assumes you have R binaries on all machines already, so, it won't solve your problem if not all Spark worker nodes have R installed.

**Comment by Harrymsys** [comment]
Is there a way to copy all the libraries from the node (where spark jobs
are triggered) to the worker node - When the spark job gets initiated ?

Is it must to install the R binaries in all nodes or possible to copy from
one node as zip ?

**Comment by yitao-li** [comment]
@Harrymsys Not at the moment. Also, I believe this is outside the scope of what `sparklyr` can meaningfully and reliably support, because of the glibc compat issues (among other issues) I mentioned above. Please just follow https://unix.stackexchange.com/questions/149451/install-r-in-my-own-directory instead.

**Comment by Harrymsys** [comment]
Is it possible to store the r lib and binaries to Hdfs and use it like this
https://stackoverflow.com/questions/49717181/how-to-use-spark-apply-bundle

**Comment by yitao-li** [comment]
@Harrymsys Not really. Spark apply bundle is designed to transfer R packages from one host to another. It cannot reliably transfer R and Rscript binaries because of the glibc version issue I mentioned above, and also because (if I remember correctly) Rscript itself makes some assumption about the directory layout of R installation. If that directory layout is altered on another host, then things will break as well.

I think you should just follow https://unix.stackexchange.com/questions/149451/install-r-in-my-own-directory

**Comment by Harrymsys** [comment]
Okay at last is it configurable to transfer r packages as zip (by providing
the source path and destination path) and transfer from one host to another
?

Also folder structure will not vary across hosts

**Comment by yitao-li** [comment]
@Harrymsys Not at the moment. That could be a feature request though if you believe zip format is in some way substially better than tar.
