### ISSUE TITLE
Using cached dataframe inside spark_apply() not working

### ISSUE THREAD

**Issue by bogdani189** [sparklyr/sparklyr#3155]
Hello! I am trying to use a cached data frame inside spark_apply(), but it seems I can't make it work. My goal would be to use the same persisted df inside each task resulting after spark_apply().
This is the code I am trying:

data <- data.frame(
id = c (1:6)
)

data_test <- data.frame(
id = c (1:5)
)

data_spark <- copy_to(sc, data,repartition=6,overwrite = TRUE)
data_test_spark <-  copy_to(sc, data_test, overwrite = TRUE)
persisted_df <- sdf_persist(data_test_spark, storage.level = "MEMORY_ONLY")
dplyr::count(persisted_df)

spark_apply(data_spark,function(id, context){

persisted_df = context$persisted_df

dplyr::count(persisted_df)
return(id)

}
,columns=list(id = "double"),  context = list(persisted_df = persisted_df),memory = TRUE)

spark_disconnect(sc)

I am getting this error: ERROR sparklyr: Session (6728) failed calling sql on 14: java.lang.IllegalArgumentException: Object not found 14

Also, by trying only with data_test_spark<- copy_to(sc, data_test, overwrite = TRUE, memory = TRUE), I am getting the same error.

I am using sparklyr 1.6.2

**Comment by yitao-li** [comment]
@bogdani189 The spark_apply context should only be used for R objects that are (1) serializable and (2) will make sense on Spark worker nodes once deserialized.

I don't think your use case satisfies (2).

Why not try the following:

- persisted_df <- sdf_persist(my_df, "MEMORY_ONLY", name = "my_persisted_df")
- And then inside your spark_apply closure:
persisted_df <- dplyr::tbl(sc, "my_persisted_df")

You can pass the name of the persisted dataframe as part of the context, but passing the reference to the dataframe object itself will not work, because the reference only makes sense with the current Spark connection you have and doesn't make sense on the worker connection.
