### ISSUE TITLE
Cannot access spark connection (sc) inside spark_apply

### ISSUE THREAD

**Issue by bogdani189** [sparklyr/sparklyr#3156]
As a follow-up to #3155, i tried inside  spark_apply closure:
persisted_df <- dplyr::tbl(sc, "my_persisted_df")

I put sc on context, but i get the following error: terminated unexpectedly: invalid connection

Is there any other way to access sc inside spark_apply? Or are we able to do this? 

Thank you very much!!!

**Comment by yitao-li** [comment]
@bogdani189 I see. I think I forgot `sc` is no longer available within the closure. I'll look into the possiblity of modifying `spark_apply()` to make the Spark worker connection acccessible.

There are 2 caveats to keep in mind though:

- The Spark worker connection is different from the first connection you created to Spark driver node. Object references that make sense for one connection won't make sense for the other.
- There are operations Spark driver nodes can perform that Spark worker nodes cannot (e.g., creating new dataframes)

**Comment by yitao-li** [comment]
@bogdani189 After thinking about this further, I'm not sure if accessing a Spark dataframe from the spark_apply worker closure is a sensible thing to do, because

- The work function is meant to carry out computations in R. Even if it could access a Spark dataframe, it would need to fetch data back from Spark to R as well (e.g., by calling `sdf_collect()`) in order to access the actual data in the Spark dataframe. Rather than having individual Spark workers perform this type of operation, it would only be more efficient to fetch the Spark data you want to work with back to R on the driver node and distribute the resulting R dataframe as part of spark_apply context.

- Supporting `dplyr::tbl()` or similar functionalities on Spark worker connection would be non-trivial

**Comment by yitao-li** [comment]
Closing this because having `sc` inside `spark_apply()` worker closure is fundamentally incompatible with the design of Apache Spark and there is no way to implement such feature in a sensible way at the moment. Also, there are alternatives to having `sc` inside the Spark worker closure.
