### ISSUE TITLE
spark_read_delta does not benefit from partitions

### ISSUE THREAD

**Issue by Adrian-S-D** [sparklyr/sparklyr#3214]
I am using Databricks witha Delta Lake in the background. Databricks runtime is 10.2, with sparklyr 1.7.2. 

```r
sc <- spark_connect(method = "databricks")
spark_read_delta(sc, read_path, memory=FALSE) %>% filter(yearMonth >= 201801) %>% filter(yearMonth < 202202)
```
is much faster than 
```r
sc <- spark_connect(method = "databricks")
spark_read_delta(sc, read_path, memory=TRUE) %>% filter(yearMonth >= 201801) %>% filter(yearMonth < 202202)
```
with the default value for memory. Thus it looks to me that with the default value sparklyr does not benefit from the partition on yearMonth of the delta files.
Timing on my single node cluster for testing purposes, was with memory=FALSE ~8 minutes runtime and with memory=TRUE it is at a stage with 12/224 jobs after ~10 minutes.

Is there an issue with my coding (first time trying that with sparklyr) or might it be a good idea to change the default of memory?

**Comment by edgararuiz** [comment]
Hi, changing `memory` will depend on what else will you be doing with the data, if it's a one time read/query, then it is usually faster to not cache. But if you are reading, and then querying several times the same data, then it is worth caching in Spark memory (`memory = TRUE`) .  Here is an article that goes deeper into this subject: https://spark.rstudio.com/guides/caching.html

Regarding the partition, consider using `sdf_repartition()`, it was an argument called `partition_by` that you can use to tell it to partition by `yearMonth` before performing your analysis. https://spark.rstudio.com/packages/sparklyr/latest/reference/sdf_repartition.html 

I'll go ahead a close this issue since none of the `spark_read_...` functions have a way to pass the `partition_by` argument at read time. 

Thanks

**Comment by Adrian-S-D** [comment]
Thanks for your answer.
From my point of view, the default value of 'memory' argument should be FALSE. 
If I work with spark and delta lake, the tables are big and will not fit into memory. If the tables fit into memory I would not use spark dataframes, but either base R dataframes or their siblings from tidyverse or data.table.
I am aware that this is a personal point of view, and thus I am fine with closing it.
