### ISSUE TITLE
how to run dist() in spark

### ISSUE THREAD

**Issue by zheguzai100** [sparklyr/sparklyr#894]
i had a big dataset, dim(dataset)= 80000+ ,700+
i wanna dist(dataset) , but it takes too large memory costs .
is there a way to accomplish it with spark(standalone) or tensorflow?
@javierluraschi

**Comment by javierluraschi** [comment]
See https://stackoverflow.com/questions/37809834/how-to-compute-the-distance-matrix-in-spark, doesn't seem Spark supports something out of the box.

However, with some work, you might be able to use `spark_apply()`:
- First, you would need to partition by row and pass the matrix (since it's not that big) into the `context` parameter.
- Then, you would have to calculate the distance in each row against all entries in the `context` rows, maybe using `purrr` and `dist()` between every two row combinations.
